### ISSUE TITLE
Getting `unknown field downloadUrl` when upgrading Enigmatica 6

### ISSUE THREAD

**Issue by shinji257** [gorilla-devs/ferium#100]
When downloading Enigmatica 6 modpack I'm getting the following error and it refuses to retrieve anything for it.
unknown field `downloadUrl`, expected one of `projectID`, `fileID`, `required` at line 8 column 35

**Comment by theRookieCoder** [comment]
The manifest that they use is not up to spec. I think it's against ToS to put download URLs in the manifest

**Comment by theRookieCoder** [comment]
The actual problem is something else so I've moved it
