### ISSUE TITLE
Furse does not support Quilt

### ISSUE THREAD

**Issue by Stick641** [gorilla-devs/ferium#103]
While trying to add "Xaero's Minimap" mod for example I get this error: 
`Adding mod... error decoding response body: invalid value: 5, expected one of: 0, 1, 2, 3, 4 at line 1 column 12716`

Steps to reproduce:
`ferium add 263420`

Happens with some other mods, including Xaero's World Map (317780) (...column 12812) and GeckoLib (388172) (...column 12929)
Arch Linux / ferium 4.1.0 / Profile is Fabric 1.18.2

**Comment by theRookieCoder** [comment]
I think this is because of CF newly added Quilt
