### ISSUE TITLE
Make even more clear that adding mods won't actually download them

### ISSUE THREAD

**Issue by KyleUltimate** [gorilla-devs/ferium#111]
## The problem
After recommending this mod to my frieinds, I found that they all have a similar problem. They always tell me, "why does my mod folder is empty! I added the mods! " I think this may be because of the order of the readme confusing them? Because in the adding mods part, it didn't even stated that you need to first do `ferium upgrade` to download them. And people don't actually read further into the readme other than the heading. "Upgrading Mods" won't make them intuitively think of "I need to do this after adding my mods!" So I suggest, putting a notice in the "Adding Mods" part of the Readme

## My solutions
Well, it's a readme problem, so I just tell them to do `ferium upgrade` but this may cause problems if the user comes from reddit or somewhere else

**Comment by theRookieCoder** [comment]
I've encountered this problem a lot actually. Some people are like, “I tried Ferium, but it never downloads anything.” So I ask them, “Did you ever run `ferium upgrade` or `ferium modpack upgrade`,” and they're like “no… what's that?”

**Comment by KyleUltimate** [comment]
Also, an extension of this issue is:
Is it possible so prompt the user to do `ferium upgrade` if this is the their first time creating a profile?
Cause my test of seeing if a program is user friendly doesn't all check in ferium.
- (x) easy to understand syntax
- () can do simple things without reading the readme
If I don't read the readme, i can probably proceed until adding mods, after that I don't know what to do!
But if ferium prompt me after tne creation of my first profile("After adding your mods, remember to do `ferium upgrade` to get them downloaded!") I could finish the whole set-up withotut even reading the readme!

**Comment by theRookieCoder** [comment]
Oh yeah that would be great idea actually!
