### ISSUE TITLE
If two of the same mod files are found, both should not be downloaded

### ISSUE THREAD

**Issue by SettingDust** [gorilla-devs/ferium#120]
## Description
Download architectury-4.4.68.jar everytime

## To Reproduce
1.18.2 Quilt add architechtury-api

## Software version
- OS (macOS/Windows/Linux) Windows
- Ferium Version (output of `ferium -V`) 4.1.1

**Comment by theRookieCoder** [comment]
I'm not really sure what you mean. Does the file download every time even if it is already downloaded?

**Comment by SettingDust** [comment]
> I'm not really sure what you mean. Does the file download every time even if it is already downloaded?

yes

**Comment by KyleUltimate** [comment]
https://github.com/gorilla-devs/ferium/issues/53
I thought this issue has been fixed?
Doesn't seem like it here

**Comment by SettingDust** [comment]
Not only architectury but cloth config

**Comment by theRookieCoder** [comment]
> #53 I thought this issue has been fixed? Doesn't seem like it here

It's not possible to fully check between platforms. The duplication checks either check the project IDs within platform, or _try_ to check between platforms using the mod name. This won't work with mods that have different names on each platform, e.g. Architectury API or Cloth Config

**Comment by theRookieCoder** [comment]
I think the best solution is to just not download mod files that are duplicated

**Comment by SettingDust** [comment]
> I think the best solution is to just not download the same mod file twice

The cloth config newest version on cf and modr isn't same XD

**Comment by theRookieCoder** [comment]
They might be having problems with minotaur, I'm believe they prefer people to use Modrinth actually.

**Comment by SettingDust** [comment]
![图片](https://user-images.githubusercontent.com/19922286/172589050-1cfac9bd-1e1d-4f2a-9148-236b2cdefa97.png)
![图片](https://user-images.githubusercontent.com/19922286/172590230-4b2913ae-ae30-42cf-bc52-102fa11e5f81.png)

**Comment by theRookieCoder** [comment]
And the 1.19 version isn't even on Modrinth yet

**Comment by theRookieCoder** [comment]
For some reason deduping in Rust seems to be kinda sketchy, dunno why
