### ISSUE TITLE
`check_mod_loader: false` won't check the mod version

### ISSUE THREAD

**Issue by SettingDust** [gorilla-devs/ferium#122]
## Description
`check_mod_loader: false` won't check the mod version
1.18.2 Quilt download `geckolib-forge-1.19-3.1.0`

## To Reproduce
```
{
  "name": "GeckoLib",
  "identifier": {
    "CurseForgeProject": 388172
  },
  "check_mod_loader": false
}
```

## Software version
- OS (macOS/Windows/Linux) Windows
- Ferium Version (output of `ferium -V`) 4.4.1
- 1.18.2 Quilt

**Comment by KyleUltimate** [comment]
I thought this issue has been fixed?
https://github.com/gorilla-devs/ferium/issues/53
Doesn't seem like it here
