### ISSUE TITLE
Support for local mod file

### ISSUE THREAD

**Issue by SettingDust** [gorilla-devs/ferium#129]
## The problem
Since the problem of third party download for cf. We have to download the mod files to the output folder. But the ferium will remove them. Need a way to add mods from local

## My solutions
Support a local addition mod folder

**Comment by theRookieCoder** [comment]
Are you talking about mudpacks? Profiles have `user` mods as described in the 4th point [in the readme](https://github.com/gorilla-devs/ferium#adding-mods)
