### ISSUE TITLE
Some commands can't be run without a profile

### ISSUE THREAD

**Issue by theRookieCoder** [gorilla-devs/ferium#131]
## Description
Only commands that need a profile should show an error if one isn't present

## To Reproduce
For example, one can't run `ferium complete` with no profiles

## Software version
- All OSs
- Ferium `v4.1.2`

**Comment by theRookieCoder** [comment]
Unfortunately, this can't be properly fixed until Polonius is released

**Comment by KyleUltimate** [comment]
Oh, so do I need to modify the AUR releases to create a temp profile so that it can run completions on a clean machine?

**Comment by theRookieCoder** [comment]
Hmm, yeah you would but I'm trying a workaround to fix this. If that works, it won't be necessary

**Comment by theRookieCoder** [comment]
Yeah I managed to figure it out
