### ISSUE TITLE
Specify output directory per mod

### ISSUE THREAD

**Issue by SettingDust** [gorilla-devs/ferium#133]
## The problem
Mod like https://modrinth.com/mod/thatorthis can load the mods in sub dir.

## My solutions
Add a flag to specify child profile or sub dir

**Comment by theRookieCoder** [comment]
So basically multiple output directory? Or some mods in some output directories and others in another?

**Comment by SettingDust** [comment]
> So basically multiple output directories? Or some mods in some output directories and others in another?

Yes. Mods in sub dir will load by the [thatorthis](https://modrinth.com/mod/thatorthis)

**Comment by SettingDust** [comment]
For I can switch config and make the sub dir as profile. It's a solution for this issue

**Comment by xane256** [comment]
Why not just have ferium output to a different folder, and manually copy the mods into the subfolders you want afterwards? Ferium already has per-profile output directories so you could manually copy the files to your specific folder structure, or maybe use profiles to put the mods there more automatically.

**Comment by theRookieCoder** [comment]
> Why not just have ferium output to a different folder, and manually copy the mods into the subfolders you want afterwards?

That would defeat the purpose of using an automation tool like Ferium

BTW, the current workaround is to just use multiple profiles with different output directories

**Comment by daenney** [comment]
Mods like ThatOrThis feel a bit redundant when using Ferium. The idea of it being that you can select a set of mods to load together from a different location. This is helpful when developing modpacks, but for someone playing the game in practice it's largely equivalent to switching between Ferium profiles. It seems odd to have output directory override for each mod when you won't need that 99.9% of the time.

I think you can already approximate this with Ferium. If you have normal profile which only has ThatOrThis on it outputting to the default `.minecraft/mods` and then additional profiles for each set of mods, with each profile having a different output directory. You can then use ThatOrThis to select which set of mods to load by pointing it to a different Ferium profile output directory.

**Comment by theRookieCoder** [comment]
As said above, I think this is an unnecessary addition that is already solved by profiles.
