### ISSUE TITLE
Support for ARM Linux

### ISSUE THREAD

**Issue by A-noximous** [gorilla-devs/ferium#134]
## Description
None of the 3 Linux builds for Ferium run on Ubuntu 20.04 and fail with `Exec format error`

## To Reproduce
1. Use `wget` to download the zip file from the latest release page
2. Extract the executable using `unzip`
3. Move the file to `/bin/ferium`
4. Run `ferium -V`

Results in `-bash: /usr/bin/ferium: cannot execute binary file: Exec format error` for all 3 executables(`gnu-gtk`, `gnu-nogui`, and `gnu-xdg`)

## Software versions
- OS: Linux Ubuntu 20.04.3 LTS AArch64
- Ferium does not run, but the release downloaded was `v4.1.3`.

## Additional Info

System `neofetch`:
![image](https://user-images.githubusercontent.com/92843602/173177378-be3f55f3-1a34-42a1-9754-c75b605a2530.png)

The `nogui` build works on my local WSL system(Ubuntu 20.04.4 LTS):
![image](https://user-images.githubusercontent.com/92843602/173177456-d38380be-fa0c-4269-b534-a841851a2847.png)

**Comment by theRookieCoder** [comment]
Ferium does not have support for arm linux yet

**Comment by A-noximous** [comment]
> Ferium does not have support for arm linux yet

Any alternatives?

**Comment by theRookieCoder** [comment]
For now, you should try compiling from source by cloning the repo and installing Rust

**Comment by A-noximous** [comment]
Will try and update.

PS: "Enhancement" label

**Comment by theRookieCoder** [comment]
I think it's fine to consider it a bug

**Comment by theRookieCoder** [comment]
I managed to compile nogui from scratch on Android, it seems to work fine. We'll have to see if cross compilation has any problems

**Comment by KyleUltimate** [comment]
Also, which arm are we talking about?
`arm` (armv5), `armv6h` (armv6 hardfloat), `armv7h` (armv7 hardfloat), and `aarch64` (armv8 64-bit).
For source packages, I could just set tne architecture to `any` and call it a day, but for binary packages, it's pretty much a necessity to know which "arm" does it support.

**Comment by imsofi** [comment]
In Nixpkgs, both [ferium aarch64-linux](https://hydra.nixos.org/build/186699129) and [ferium aarch64-darwin](https://hydra.nixos.org/build/187739077) build correctly. So ARM is properly supported by ferium, but the releases page does not currently ship with an arm64 linux package.

So currently you would need to use something like `cargo install ferium` to install on arm. Alternatively, there is also the nix packages that are maintained outside this repo, which requires nix to be installed, but runs with `nix run nixpkgs#ferium`.
