### ISSUE TITLE
Sync mod profiles with other machines

### ISSUE THREAD

**Issue by jfkw** [gorilla-devs/ferium#136]
## The problem

Players need to synchronize their installed mods to join local Minecraft servers together. One user starts the server and others joining must have at least those mods installed to join. Configurations change frequently. My personal use case is for family members playing on the same LAN. Discoverability on the LAN would be helpful.

## My solutions

- Add a daemon mode to `ferium` that runs continually and listens for network connections.
- Local user needs to be able to issue commands through a trusted connection. This would facilitate read-only clients in less-trusted networks.
- Create a `systemd` unit to run `ferium` in daemon mode/
- `ferium` in daemon mode publishes its mod profile list
- `ferium` in daemon mode uses a protocol to allow clients to discover it as a server.
- Local `ferium` clients can activate remote profile in a similar way to local profiles, likely with a (remote) indicator.
- Local `ferium` clients can import remote profiles as local, although these will no longer stay in sync
- Longer term, a P2P model where multiple clients could create and edit mod profiles would be useful

**Comment by jfkw** [comment]
I am interested to contribute to implementation of the feature once a there is consensus on a design and acceptable dependencies.

**Comment by Eskaan** [comment]
I think that is way out of scope for this project

**Comment by theRookieCoder** [comment]
I agree. Ferium stores its config in a file, and it's pretty easy to sync that file across machines (e.g. I symlink mine from Google Drive). Even _if_ this feature is implemented, there is not need for such a complex solution.
