### ISSUE TITLE
Manager installs mod that is incompatible with currently installed fabric loader version

### ISSUE THREAD

**Issue by feelingnothing** [gorilla-devs/ferium#137]
## Description
In the title

## To Reproduce
1. Install fabric loader version 0.14.6 (one minor version behind last one on current date of June 12, 2022)
2. Install Fabric Kotlin Language library
3. Launch Minecraft

## Software version
- OS: Windows 21H2
- Ferium Version: 4.1.3

**Comment by theRookieCoder** [comment]
It is simply impossible to check the mod loader version that a mod is compatible with

**Comment by SettingDust** [comment]
> It is simply impossible to check the mod loader version that a mod is compatible with

The mod manifest may contains

**Comment by feelingnothing** [comment]
It does in manifest, but I guess you know more than me 🧐
