### ISSUE TITLE
Override compatibility check when adding mods

### ISSUE THREAD

**Issue by Robinerra** [gorilla-devs/ferium#142]
## The problem
We're in between versions 1.18-1.19 of Minecraft and not all mods have been updated to 1.19 yet, so I have to write down all the mods that haven't been updated to 1.19 in a file somewhere to check on every now and then so I can add them to my 1.19 profile once they're updated. This is annoying af to keep track of.

## My solutions
Have the ability to add version imcompatible mods into the profile (but give a message notifying this has happened) and check if they've been updated on ``ferium upgrade``, then download if they're compatible. This would save a huge hassle of what I described above.

Thank you to all the contributors <3

**Comment by theRookieCoder** [comment]
You can actually add all your regular mods. Then when upgrading all the mods that are compatible will still be downloaded.

**Comment by theRookieCoder** [comment]
Added in 8fa2dc0f9c30d60cf01a124221fecbceea333c88
