### ISSUE TITLE
`notenoughanimations-fabric-1.6.0-mc1.18.2.jar` in `user` is copied every time

### ISSUE THREAD

**Issue by SettingDust** [gorilla-devs/ferium#144]
## Description
`notenoughanimations-fabric-1.6.0-mc1.18.2.jar` in `user` be copies everytime

## Software version
- OS (macOS/Windows/Linux) Windows
- Ferium Version (output of `ferium -V`) 4.1.4

**Comment by theRookieCoder** [comment]
Are you sure you don't have the mod added too? Otherwise I have no idea what can cause this

**Comment by SettingDust** [comment]
> Are you sure you don't have the mod added too? Otherwise I have no idea what can cause this

Haven't xd

**Comment by HellishINC** [comment]
I've had this issue as well though it hasn't caused any major issues as newer versions of forge (cant comment on fabric) will ignore duplicates and load the newest.

In my particular case the issue occurred with "libferret" so I can say that it isn't mod specific.
