### ISSUE TITLE
Waring duplicate for non-duplicate 

### ISSUE THREAD

**Issue by SettingDust** [gorilla-devs/ferium#145]
## Description
Every time `Warning: 1 duplicate files were found ItemBorders-1.18-fabric-1.1.5.jar. Remove the mod it belongs to`
Can't find why is it conflicting. It's fine with a new profile with it. May need more info for the waring?

## Software version
- OS (macOS/Windows/Linux) Windows
- Ferium Version (output of `ferium -V`) 4.1.4

**Comment by theRookieCoder** [comment]
Check your config file to see if the mod is specified multiple times. You can also list your mods to see if it's duplicated

**Comment by SettingDust** [comment]
> Check your profile to see if the mod is specified multiple times. You can also list your mods to see if it's duplicated

It's not. Have searched with vsc in config.json
![图片](https://user-images.githubusercontent.com/19922286/173843795-4fd4f23f-d4e6-49c1-b995-475b611feb12.png)

**Comment by theRookieCoder** [comment]
Could you send your config file so that I can test on it?

**Comment by SettingDust** [comment]
> Could you send your config file so that I can test on it?

https://pastes.dev/OpqIzadgWi

**Comment by theRookieCoder** [comment]
Your config does have the ItemBorders mod duplicated, but the name of the duplicate is `Advancement Plaques [Fabric]`
