### ISSUE TITLE
Support colouring on Windows conhost

### ISSUE THREAD

**Issue by supsm** [gorilla-devs/ferium#148]
## Description
What is the bug?
Certain (most) commands cause formatting codes to be printed, instead of interpreted properly, on windows

## To Reproduce
What did you do to encounter this bug?
Run `ferium list` in windows cmd.exe. Note that `ferium help` works properly, and appears to be the only one to do so.

## Software version
- OS: Windows 11
- Ferium Version: 4.1.5

## Additional information
`SetConsoleMode` with `ENABLE_VIRTUAL_TERMINAL_PROCESSING` in C/C++ WinAPI is usually used to deal with issues like these. I'm not sure what the rust equivalent of this is, but the `help` command does work properly (I don't really understand rust, so cannot locate the issue and open a pr).  
Windows Terminal (rather than cmd.exe) does work properly, likely because the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag is set by default.  

`help` command (correctly displayed):
<img width="540" alt="image" src="https://user-images.githubusercontent.com/60897356/174919240-eef3afad-4097-420d-86e7-cdd44bae5c5f.png">

`list` command (incorrectly displayed):
<img width="503" alt="image" src="https://user-images.githubusercontent.com/60897356/174919293-735b2e1d-b523-4b6d-b0ae-cef742f84c84.png">

`list` command (correctly displayed, in Windows Terminal):
<img width="362" alt="image" src="https://user-images.githubusercontent.com/60897356/174919349-fe8c016b-36a7-4596-b0f6-cfd9d1ad386c.png">

**Comment by theRookieCoder** [comment]
OK firstly, the help command works because that is auto-generated by the [clap](https://docs.rs/clap) argparser. The reason I'm not using that library is because it's much more complicated than what I'm currently using. I'll have to experiment with more rust terminal colour providers to see what works. In the meantime, you can use Windows Terminal. (which is much better anyways. I'm curious, why would you still want to use conhost apps like cmd and powershell)

**Comment by supsm** [comment]
Just more used to it, really
No matter what I do, I don't think I can replicate cmd in windows terminal exactly

**Comment by Nekkowe** [comment]
One reason for using Windows Terminal is that it's completely unavailable pre-Win10.

I'm currently getting the same formatting codes in cmd:
![image](https://user-images.githubusercontent.com/28980049/179491563-82f2d10f-3fc1-427e-ac1f-443edda1b674.png)

**Comment by KyleUltimate** [comment]
There are alternatives to windows terminal(wezterm alacritty to name a few)!
I believe they will all work. Because they're linux counterpart all does :tater:

**Comment by theRookieCoder** [comment]
I unfortunately don't think it's worth rewriting all the terminal outputs into a different colour library, and `colored` is optimal in terms of code. I'm going to disable colour for conhost, and of course you can just set `$NO_COLOR` to disable colour too.

**Comment by theRookieCoder** [comment]
It seems I need to use [this winapi function](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Console/fn.SetConsoleMode.html) to enable ansi escape codes for conhost.

**Comment by CatGamer23** [comment]
In python, in order to enable ANSI codes, we call `os.call('')` because of a bug in cmd.exe (cmd.exe enables VT mode, but doesn't disable it on exit)

Maybe something similar would work in this case?

**Comment by theRookieCoder** [comment]
I read a bit about this workaround and don't really get why it works, but I think it makes use of the python interpreter itself, but Rust obviously doesn't have such a runtime.

**Comment by theRookieCoder** [comment]
Hmm that was stupid of me, turns out there is [a function](https://docs.rs/colored/latest/x86_64-pc-windows-msvc/colored/control/fn.set_virtual_terminal.html) in coloured itself that enables support for `conhost`.
