### ISSUE TITLE
Support for "fuzzy" removal

### ISSUE THREAD

**Issue by JustSimplyKyle** [gorilla-devs/ferium#150]
## The problem
I want to remove mods without first doing a fuzzy search via `sk` in `ferium list`. A lot of mods has super long names, for example NMUK, which the full name is "No More Useless Keys - NMUK" which is too long to remember. 

## My solutions
Currently I first do a fuzzy search in ferium list, then copy the results into ferium.
![image](https://user-images.githubusercontent.com/68589851/175286373-b7b8aa24-c993-482a-a602-7dfafd9fd7aa.png)
I hope that ferium can intergrate sk(or use whatever fuzzy search library you wish to use) when doing `ferium remove mymodname`

**Comment by theRookieCoder** [comment]
Moved to #163
