### ISSUE TITLE
Mod won't add if optional dependencies are blocked

### ISSUE THREAD

**Issue by HellishINC** [gorilla-devs/ferium#152]
## Description
Mods aren't added when optional depends are denied from third party programs.

## To Reproduce
ferium add 248020

edit: other mods that fail to add
628539

This attempts to add "Flux Networks" for 1.18.2 and one is lead to believe it was successful but in reality it fails as it terminates when an *optional* dependency is listed as "denied third party".

```
~ 
12:04:29 AM   >> $ ferium add 248020
Adding mod... ✓ Flux Networks
Checking optional dependency... × Not compatible, try running `ferium add 352656`
Checking optional dependency... ✓
✔ Add optional dependency Applied Energistics 2 (https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)? · no
Checking optional dependency... The developer of this mod has denied third party applications from downloading it
````

```
Entangled                                     CurseForge 301034
Farmer's Delight                              CurseForge 398521
Farmer's Respite                              CurseForge 551453
Fast Leaf Decay                               CurseForge 230976
FastSuite                                     CurseForge 475117
Feature NBT Deadlock Be Gone                  CurseForge 560323
FerriteCore (Forge)                           CurseForge 429235
Flywheel                                      CurseForge 486392
Forbidden and Arcanus                         CurseForge 309858
GeckoLib                                      CurseForge 388172
````

This is one example of many that I've encountered but failed to realize it was happening until a player mentioned it after days of playing.

## Software version
- OS: Arch Linux.
- Ferium Version:  4.1.5

## Additional information

This makes sense if a *required* depends is blocked however optionals should simply be ignored/skipped.

Perhaps a --noopt flag.

Currently one is required to download and update the mod manually.

I really wish CF weren't so greedy.

**Comment by theRookieCoder** [comment]
Bad implementation of #121, I think I'll just catch all errors and output them as a warning
