### ISSUE TITLE
Support for minor game version overrides

### ISSUE THREAD

**Issue by JustSimplyKyle** [gorilla-devs/ferium#154]
## The Problem
Some mods only got 1.18 tagged in their curseforge, so if I want it to use it in 1.18.2, I have to disable tne game version check. This work for a while, untill the mod releases a 1.19 version, which ferium decided to download that instead. So I proprse a flag that can partially disable the mod check(only checks for major versions)

**Comment by theRookieCoder** [comment]
Funny, this feature was actually there but I removed it after check overrides were introduced. This should be just like those right?

**Comment by theRookieCoder** [comment]
Moved to #155
