### ISSUE TITLE
Support for curseforge key override in runtime

### ISSUE THREAD

**Issue by KyleUltimate** [gorilla-devs/ferium#157]
## The problem
Well, the current way to change the curseforge key is by manually editting the source code. I hope that it's possible to implement a runtime equivalent. That reads CURSEFORGE_API_KEY from `env`

**Comment by xane256** [comment]
Related note: the env name for the config is not documented

**Comment by theRookieCoder** [comment]
It is
https://github.com/gorilla-devs/ferium/blob/main/README.md?plain=1#L71
