### ISSUE TITLE
Display the ID of dependencies that are being checked/installed

### ISSUE THREAD

**Issue by ST-DDT** [gorilla-devs/ferium#158]
## The problem

````
$ ferium add 393442
Adding mod... ✓ LambDynamicLights
Adding required dependency... ✓ Already added
Adding required dependency... ✓ Already added
````

This command adds two dependencies, but I don't know which ones.

## My solutions

Print the name of the dependency, if it gets checked/installed.

````
$ ferium add 393442
Adding mod... ✓ LambDynamicLights
Adding required dependency: foobar ✓ Already added
Adding required dependency: test ✓ Already added
````

ferium 4.1.5

**Comment by theRookieCoder** [comment]
This is not fully possible because the only dependency information we get is the project ID, so only that can be displayed.
