### ISSUE TITLE
curseforge modpacks won't be downloaded

### ISSUE THREAD

**Issue by m00nlygreat** [gorilla-devs/ferium#160]
## Description
it won't download modpacks saying:
WARNING: Files in your output directory may be overwritten by modpack overrides

## To Reproduce
I tried to download a modpack named Create: Above and Beyond
project ID of which is 542763

## Software version
- Windows 10
- Ferium Version 4.1.5

## Additional information
![image](https://user-images.githubusercontent.com/29726529/176693617-dbd43d29-920b-42bf-a1b6-d7d331b50b8f.png)

**Comment by theRookieCoder** [comment]
That's just a warning.

The only command that downloads and installs anything are the `ferium upgrade` and `ferium modpack upgrade` commands. The other commands just edit the config file and perform some checks.
