### ISSUE TITLE
Confirm with the user before downloading mods

### ISSUE THREAD

**Issue by DarkShadow44** [gorilla-devs/ferium#162]
## The problem
Sometimes it would be nice to now what mods have updates available, so I can check before updating them all.

## My solutions
Add listing for all upgradable mods.

**Comment by Eskaan** [comment]
Add `--pretend` option to the upgrade subcommand

**Comment by DarkShadow44** [comment]
I assume this a suggestion how to implement it, not something that should already work?

**Comment by theRookieCoder** [comment]
Would be resolved by #49
Basically normally there will be a y/n prompt. If `--force` is used, it will download all the files no matter what, and if `--dry-run` is used, it will stop after version resolution and won't download anything.

**Comment by theRookieCoder** [comment]
Duplicate of #49
