### ISSUE TITLE
Show which mods are missing for a major version upgrade

### ISSUE THREAD

**Issue by DarkShadow44** [gorilla-devs/ferium#164]
## The problem
Let's say I want to upgrade 1.18.2 to 1.19. Right now I have to check all mods manually before I can decide whether I want to make the jump.
It would be nice to have a listing of all mods that are not yet for 1.19, so I don't have to check all mods individually.

## My solutions
Add a command that takes a major minecraft version and lists all the mods that are in the current profile but not available for the requested version.

**Comment by theRookieCoder** [comment]
You can just switch your profile to 1.19 and upgrade. All the mods that are compatible will be resolved and those which aren't will error out. The `--dry-run` flag would also be useful in this case, see #49

**Comment by DarkShadow44** [comment]
Sure, that would work. But wouldn't it be easier to temporary switch the profile and filter out all the mods that could be installed? Would be better for usability, and since the features mostly exist already, shouldn't be too hard to implement either, right?
