### ISSUE TITLE
Fails to add the carpet-extra mod from the github releases.

### ISSUE THREAD

**Issue by opsaaaaa** [gorilla-devs/ferium#168]
## Description

It fails to add the carpet-extra mod from the github releases.
However it succeeds with the main fabric-carpet mod.

## Replication

Given I have created a profile for 1.19 fabric mods and its selected.
And both fabric-carpet and carpet-extra have releases available for 1.19

When I use `ferium add gnembon/carpet-extra`
Then I get `Adding mod... The project/repository is not compatible`

When I use `ferium add gnembon/fabric-carpet`
Then I get `Adding mod... ✓ fabric-carpet`

## Additional information
I can't see a obvious difference in the two repositories that would cause this.
The tag format looks the same to me. And the download file names have similar formats as well.

The carpet extra mod is not available on Modrinth or Curseforge as far as I can tell.
Otherwise I would just use one of those.

## Relevant links

[gnembon/fabric-carpet](https://github.com/gnembon/fabric-carpet/releases)
[gnembon/carpet-extra](https://github.com/gnembon/carpet-extra/releases)

## Software version
- OS (Linux)
- Ferium Version (ferium 4.1.5)

**Comment by theRookieCoder** [comment]
`ferium add gnembon/carpet-extra --dont-check-mod-loader`

**Comment by opsaaaaa** [comment]
Yup `ferium add gnembon/carpet-extra --dont-check-mod-loader` worked
