### ISSUE TITLE
Support for Modrinth API `embedded` dependency relation

### ISSUE THREAD

**Issue by Zekiu** [gorilla-devs/ferium#169]
## The problem
Everytime you try to add a mod from Modrinth that has an embedded dependency (like [Horse Buff](https://modrinth.com/mod/horsebuff/version/1.19-2.0.1), Ferium doesn't recognize it and doesn't add the mod.

![image](https://user-images.githubusercontent.com/68301723/177052061-240d7ab8-6de5-42f3-a159-f99afa87ad4c.png)

## My solutions
Add support for Modrinth's "embedded" dependency tag

**Comment by Eskaan** [comment]
This is the wrong repo, this is a Ferinth issue. The Dependency Type was added a few days ago so it's not implemented yet. That is why the dependency resolution fails.

**Comment by theRookieCoder** [comment]
> The Dependency Type was added a few days ago

btw where do these api changes get announced? I can't find them on the announcements channel.

**Comment by theRookieCoder** [comment]
Ach, right #twitter-feed I remember now! Any ways I think the @API Announcements role will be used from now on

**Comment by wafflecoffee** [comment]
Yep, our bad for not announcing API changes properly until recently. Twitter isn't really suitable for that since it does a lot more than just API announcements.

**Comment by terminalmaid** [comment]
can be fixed by updating ferinth on crates.io and using the newer version now
