### ISSUE TITLE
Isolated `complete` subcommand code does not return

### ISSUE THREAD

**Issue by imsofi** [gorilla-devs/ferium#172]
## Description
When running the command `ferium complete bash` you will get an error message:
`thread 'main' panicked at 'internal error: entered unreachable code', src/main.rs:102:41`

## To Reproduce
Build tag `v4.1.6`.
Attempt to run the command `ferium complete bash`.

## Software version
- OS: `Fedora 35` 
- Ferium Version: `ferium 4.1.6`

**Comment by theRookieCoder** [comment]
https://github.com/gorilla-devs/ferium/issues/139#issuecomment-1186535256
