### ISSUE TITLE
Windows version can't connect to the internet

### ISSUE THREAD

**Issue by DuendeInexistente** [gorilla-devs/ferium#178]
## Description
On linux, ferium runs fine. In windows, both the msvc and gnu versions check the internet connection and fail. I tested this at a friend's W10 computer and in a wine instance (Set to windows 7) in my ubuntu computer, both with the same results. Him running as admin didn't help, and I don't know any way to get a debug output going.

## To Reproduce
Run ferium in windows.

## Software version
- OS Windows 10 & Wine set to W7 in ubuntu
- 4.1.8

## Additional information
[config.txt](https://github.com/gorilla-devs/ferium/files/9162712/config.txt)
This is the json we used.

**Comment by theRookieCoder** [comment]
Did you _thoroughly_ check that Windows is actually properly connected to the internet? Maybe `ping google.com` for example?

**Comment by theRookieCoder** [comment]
Just confirmed, ferium 4.1.8 works fine on Windows 11
