### ISSUE TITLE
Not needed error message(found at 10 clone)

### ISSUE THREAD

**Issue by KyleUltimate** [gorilla-devs/ferium#180]
## Description
When you have a unstablish internet connection, sometimes it just doesn't quite able to fetch the mod information.
So it spits out an error, which I expect, but what I didn't expect is it spit out a strange error.
![image](https://user-images.githubusercontent.com/68589851/180588558-d21bd965-579a-4f4e-848b-9e452b476efa.png)

## To Reproduce
It's quite difficult actually, if you just remove your internet when doing feruim upgrade, the upgrade just hangs, instead of pauses and exit

## Software version
- OS -> arch linux
- Ferium Version -> 4.1.8

## Additional information
It might not be my internet being unstable tho, it might be just something else!
it could be my DNS blocking(adguard home) interfereing, but that also doesn't make sense, because on second try, everything works.

**Comment by theRookieCoder** [comment]
That's just the error from reqwest. The network request that has to be done to access the api is to resolve the domain name, and since it's not connected to the internet, that fails so that's what it is saying.
