### ISSUE TITLE
Switch to `musl` to increase backwards compatibility

### ISSUE THREAD

**Issue by Phoenix-Starlight** [gorilla-devs/ferium#184]
## The problem
Is your feature request related to a problem? Please describe it.
Not really a problem, just backward compatibility.
## My solutions
Describe any number of solutions you've thought of.
The solution is to build within Ubuntu 18.04. (Alternatively, compile everything against Ubuntu 18.04 libc which is 2.27)
I understand that it's to be phased out at April 2023, so it's not a great loss if this is closed.

**Comment by theRookieCoder** [comment]
Ah jeese I guess I should just switch to musl

I'll have to test you performance on both, and then I'll migrate to musl

**Comment by Phoenix-Starlight** [comment]
I assume musl is portable and will not suffer from symbol LIBC_XX not found?

**Comment by Phoenix-Starlight** [comment]
And thanks, now I won't have to go crazy trying to modify the actions
to build correctly.
