### ISSUE TITLE
Possible solution to "manual" mods

### ISSUE THREAD

**Issue by 64-Tesseract** [gorilla-devs/ferium#187]
## The problem
Ferium cannot distinguish between mods automatically installed and ones the user doesn't want to modify.

## My solution
2 mods folders will exist under `.minecraft`, the main `mods` folder that Minecraft uses & a new `mods-manual` folder. After running `upgrade`, Ferium will do what it needs to in `mods`, and then symlinks (or just copies) the contents of `mods-manual` into `mods`.

Either Ferium could do this automatically, or it could simply run a user-defined script after completing `upgrade` that symlinks the files.
```sh
? Which setting would you like to change ›
  Mods output directory
❯ Mods input directory    OR    Post-upgrade executable
  Minecraft version
  Mod loader
  Profile Name
  Quit
```
At the moment I've written a simple bash script to make symlinks, but it's annoying to have to navigate to it every time I install a new mod.

**Comment by theRookieCoder** [comment]
Already existing feature

[Adding Mods](https://github.com/gorilla-devs/ferium#adding-mods) "External Mods"

**Comment by 64-Tesseract** [comment]
...Oh.

Welp, good to know - thanks for responding lol
