### ISSUE TITLE
Add option for other versions when selected version is not availible 

### ISSUE THREAD

**Issue by SpigotDE** [gorilla-devs/ferium#192]
A lot of mods are not updated to Version 1.19.2 , so i wanna use 1.19.1 or 1.19 if availible ( the newest one but not 1.18.2 or below
( So the highest in 1.19.x )

Is there a way to achieve this in Ferium 4.1.10 ?

**Comment by MopsTMC** [comment]
You can add any mod you like by putting it in a user directory in your mods folder, regardless of version. All ferium will do is copy the files in there to the actual mods directory. Check the last bullet of the [Adding mods](https://github.com/gorilla-devs/ferium#adding-mods) section

**Comment by theRookieCoder** [comment]
Would be fixed by #155, unfortunately it's not currently possible to achieve this in the current ferium version. Although as MopsTMC pointed out it is possible to use the user mods feature as a workaround.

**Comment by MopsTMC** [comment]
No worries! I think ferium is in a great state right now and I appreciate the amount of work put into it immensely. It's been incredibly useful and I'm pretty sure it's the best at doing it's job currently.
