### ISSUE TITLE
Unable to remove mods from profile

### ISSUE THREAD

**Issue by Lancelotbronner** [gorilla-devs/ferium#193]
## Description
Once a mod is added I'm unable to remove it

## To Reproduce
```powershell
ferium add plasmo-voice
Adding required dependency... ✓ Fabric API
ferium add plasmo-voice
Adding mod... The project/repository has already been added
ferium remove plasmo-voice
A mod called plasmo-voice is not present in this profile
```

## Software version
- OS Windows
- ferium 4.1.10

## Additional information
I've also tried the modrinth id and it doesn't work.

**Comment by theRookieCoder** [comment]
if you're specifying the mod to remove as an argument, it has to match with the _name_ of the mod, not the ID/slug. You can also not provide any arguments, and it will give you selection thing that you can use too.
