### ISSUE TITLE
Add ability to bundle non Curseforge/Modrinth mods

### ISSUE THREAD

**Issue by CorneliusCornbread** [gorilla-devs/ferium#198]
Some mods, especially in-development versions, aren't distributed on Curse or Modrinth. An example would be the latest versions of Tinker's construct which can currently only be downloaded off of GitHub.

## My solutions
Simply allow the modpack to bundle the jar itself, it'd be a good idea to provide a warning saying something like:
`WARNING! The following mods are not distributed via Modrinth or Curseforge and could be dangerous: ExampleMod1.jar, ExampleMod2.jar`

I know that there's already support for GH releases, but on occasion, mods will use CI builds to distribute their beta releases. Or will distribute them on another site entirely, like GalacticCraft used to.

Also, I know that these mods aren't distributed on CF/Modrinth for a reason, they're in early alpha, I still want to play them with friends nonetheless, it's just a matter of whether or not I can use ferium to do it.

**Comment by theRookieCoder** [comment]
I don't really understand how modpacks 'bundle the jar itself'? If it's in the overrides, then ferium already copies that over, or are you talking about exporting modpacks?
