### ISSUE TITLE
Enhancment: version toggles

### ISSUE THREAD

**Issue by EysseW** [gorilla-devs/ferium#199]
## The problem
Is your feature request related to a problem? Please describe it.
Many 1.19.2 mods work perfectly fine on 1.19, but ferium only installs or updates if it is the correct version.

I'd suggest making a toggle in the settings on a profile, defining whether or not subversions should matter.

**Comment by theRookieCoder** [comment]
#155

**Comment by EysseW** [comment]
This thread doesn't mention a profile toggle, does it?

**Comment by theRookieCoder** [comment]
I don't get it?

These fallback options will always be specified per profile, with mods overriding them if necessary.

**Comment by EysseW** [comment]
I don't get you... Anyway, my idea is that there is a setting in the profile stating if subcommands should be considered in upgrades and adding mods, so you don't have ta type --dont-check-game-versien every single time.

**Comment by EysseW** [comment]
I meant subversions with subcommands. e.g. 1.19.2 and 1.19
