### ISSUE TITLE
Add profile duplicating.

### ISSUE THREAD

**Issue by redstonerti** [gorilla-devs/ferium#202]
## The problem
My server and client have slightly different mods. There are >150 mods and instead of being able to add them to one client, duplicate it and make small changes to the client and server, I have to manually add each mod and each id to both profiles.

## My solutions
Just allow me to duplicate profiles. Thanks.

**Comment by theRookieCoder** [comment]
`> ferium profile create --help`

`ferium-profile-create 4.1.10`
Create a new profile
Optionally provide all the options, to create the profile without the UI
**Use the import flag to import mods from another profile**
```
USAGE:
    ferium profile create [OPTIONS]

OPTIONS:
        ...
        --import [<IMPORT>]
             Copy over the mods from an existing profile
             Optionally, provide the name of the profile to import mods from
```
