### ISSUE TITLE
Can't make exceptions for mods

### ISSUE THREAD

**Issue by redstonerti** [gorilla-devs/ferium#203]
## Description
Some mods don't tag their mod as being compatible with the latest version. e.g. Better ping display's latest release is supposedly for 1.19 but the mod also works for 1.19.2. Ferium not only doesn't allow you to add the mod, but it also removes it from your mods folder whenever you do ferium upgrade.

Another example is Rat's mischief. The author doesn't allow you to download the mod from third party apps. That's fine. But I should be able to add it to my mods folder manually and tell ferium to not remove it.

Thanks.

**Comment by theRookieCoder** [comment]
> it also removes it from your mods folder whenever you do ferium upgrade

> I should be able to add it to my mods folder manually and tell ferium to not remove it

Read 'external mods' under [Adding Mods](https://github.com/gorilla-devs/ferium#adding-mods)

**Comment by redstonerti** [comment]
Fair enough. Thanks for informing me of the existing solutions. To be fair, I was looking at the rust docs of ferium, which do not have that section.
![image](https://user-images.githubusercontent.com/48157961/189498448-e97a541b-7317-4ad2-a49d-9c786c034924.png)
![image](https://user-images.githubusercontent.com/48157961/189498467-76b77f6b-e392-4731-8d8e-13c0c4fa3459.png)

**Comment by theRookieCoder** [comment]
THe rust docs are identical to the github readme, you were probably looking at an older version of the docs (common when using links form google). [Here](https://docs.rs/crate/ferium/latest) is the latest docs
