### ISSUE TITLE
Ferium can't remove mods from its own list

### ISSUE THREAD

**Issue by ladmol** [gorilla-devs/ferium#206]
## Description
Mods remain in the list after deletion

## To Reproduce
Use any terminal.
Ferium cannot remove mods from its own list. After the `ferium remove` command (it doesn't matter if you specify the exact name or just select it from the list), the mod remains in the `ferium list`

## Software version
- OS Win10 21H2 19044.2006
- Ferium Version  4.1.10

## Additional information
BTW, this tool is so easy to use. Thanks a lot!

**Comment by theRookieCoder** [comment]
Just to confirm, when selecting using the GUI you are selecting the mods using the space bar and pressing enter right? And after you run the command or select the mods the program exits without any errors?

I can't replicate this
