### ISSUE TITLE
Support static HTTP(S) url's as a download source

### ISSUE THREAD

**Issue by N0tJust1n** [gorilla-devs/ferium#208]
## The problem
Some mods have auto-build servers with static url's that host the latest build artifacts that may not be available via modrinth or curse.

## My solutions
Allow for users to manually enter in an http address as an install option. ie: `ferium install https://ci.opencollab.dev/job/GeyserMC/job/Geyser-Fabric/job/master/lastSuccessfulBuild/artifact/build/libs/Geyser-Fabric.jar` or `ferium install --http yadayadayada.com/mod.jar`

This would allow ferium to download and update from such sources. Versioning and modloader detection may be an issue but I believe that is an existing problem with GitHub downloads anyway.

**Comment by theRookieCoder** [comment]
This functionality would fall under #155
