### ISSUE TITLE
Factoring name pattern when checking mod existence

### ISSUE THREAD

**Issue by strdsk** [gorilla-devs/ferium#213]
## The problem
I'm using MultiMC and as you know, it has mod disabling features, by suffixing `.disabled` on file path. The problem is, I need to reenable all mods to prevent ferium from unnecessary redownloading.

## My solutions
Add options for user to add patterns to be used on file check besides the normal checking per profile basis?. Optionally, add something like `${MOD_NAME}.disabled` by default, fixing this problem for MultiMC users and at the same time an example for end user.

**Comment by theRookieCoder** [comment]
Moved to #219
