### ISSUE TITLE
Picking the wrong version (older) instead of newer ones

### ISSUE THREAD

**Issue by strdsk** [gorilla-devs/ferium#215]
## Description
It's downloading an older version while newer one exist.

## To Reproduce
Use FML. Then, try to download [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus/download/3973908) or [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium).

For example, in Rubidium as of 11 Oct, the desired one is [Rubidium mc1.19.2-0.6.2](https://www.curseforge.com/minecraft/mc-mods/rubidium/files/3973894) (uploaded on Sept 9)
Instead, it will downloads the older one, [Rubidium mc1.19.2-0.6.1](https://www.curseforge.com/minecraft/mc-mods/rubidium/files/3929559) (uploaded on Aug 11)

## Software version
- Windows
- Ferium 4.2.0

**Comment by theRookieCoder** [comment]
I assume your profile is set to `1.19`? If so, the issue is that `0.6.2` says it only works on `1.19.2` while `0.6.1` says that it works on `1.19.2`, `1.19.1`, and `1.19`. This could be intentional or a mistake by the publisher.
