### ISSUE TITLE
Force third party clients curseforge resictions solution.

### ISSUE THREAD

**Issue by AntonIXO** [gorilla-devs/ferium#221]
## The problem
Some mods restrict downloading for non official clients, but I found one witch force it.
[Curseforge-cli](https://github.com/North-West-Wind/CurseForge-CLI/blob/3ff33b814aecd892ac87ae01577e21e6918c011d/src/ml/northwestwind/Profile.java#L199)
[Downloading code](https://github.com/North-West-Wind/CurseForge-CLI/blob/3ff33b814aecd892ac87ae01577e21e6918c011d/src/ml/northwestwind/Utils.java#L51)

## My solutions
We port such functionality to ferrium to download mods faster.

**Comment by theRookieCoder** [comment]
I'm well aware of this method, however it would probably get our API key revoked. It also doesn't solve the problem, which is that those who disabled third party downloads wish to get ad revenue. I think #149 is a good compromise between automation and respecting the mod author's wish to show ads.
