### ISSUE TITLE
Bug: Not working with Crafting Tweaks mod

### ISSUE THREAD

**Issue by jmc529** [gorilla-devs/ferium#223]
## Description
[Crafting tweaks](https://www.curseforge.com/minecraft/mc-mods/crafting-tweaks/files/3330406) does not add to a 1.16.5 profile "Adding mod... The project/repository is not compatible". However there is a valid file.

## To Reproduce
freium profile create -> make 1.16.5 profile
ferium add 233071

## Software version
- Windows
- Ferium 4.2.0

**Comment by theRookieCoder** [comment]
The mod loader is not specified. Use the `--dont-check-mod-loader` when adding this mod.
