### ISSUE TITLE
Can complete first setup in Nobara 36/Fedora (no GUI)

### ISSUE THREAD

**Issue by Mathew420w0** [gorilla-devs/ferium#233]
## Description
When first setting up the ferium profile, if I choose to change the mod directory, it gets stuck forever; if I set it to the default and I get to the mod loader selection, then the interface doesn't let me select the loader in any way,  instructions unclear as to how to use the interface (no GIU)

## To Reproduce
run 'ferium profile create' in my operating system

## Software version
Nobara Linux 36
Ferium -V 4.2.2 (no GIU)
Homebrew -V 3.6.11
done through SSH with Ubuntu 22.04.1 LTS

## Additional information
trying to run set up the program for the first time, and I can't figure out how to select the information in the profile setup.

**Comment by theRookieCoder** [comment]
I believe Nobara would use GNOME too? If so the GUI file dialogue should work, not sure why it wouldn't but I will check again. When selecting a loader you have to use the arrow keys to navigate the options. If this doesn't work then it's probably an issue with SSH.

**Comment by theRookieCoder** [comment]
Ah I just realised that the GUI file dialogue wouldn't work through SSH. If you want to use SSH only and no GUI, you have to use the no-gui version, which isn't on Homebrew.
