### ISSUE TITLE
Don't copy user mods when Quilt is used

### ISSUE THREAD

**Issue by magneticflux-** [gorilla-devs/ferium#234]
## The problem
The latest beta of the Quilt loader loads mods from nested directories not starting with `.`. This causes the `user` directory to be loaded, leading to duplicate mods.

https://github.com/QuiltMC/quilt-loader/pull/135

## My solutions
Use `.user` just like `.old` already does.

**Comment by theRookieCoder** [comment]
The current workaround is to just put the user mods in a different folder (e.g. rename `mods/user` to `mods/usermods` or something). That way it won't interfere with ferium's downloading, but the folder will be left alone and Quilt will load from that.

**Comment by theRookieCoder** [comment]
Btw I'm not going to be renaming the user folder to be hidden, I'm going to just disable copying user mods when Quilt is selected.
