### ISSUE TITLE
gnembon/carpet-extra not compatible

### ISSUE THREAD

**Issue by W1llDu** [gorilla-devs/ferium#235]
## Description
Cannot add carpet-extra as mod

## To Reproduce
Install ferium 
Make profile
Try to add ferium/carpet-extra

## Software version
- OS Oracle Linux 7.9
- Ferium Version 4.22

**Comment by theRookieCoder** [comment]
It's probably an error with version resolution, see [this page](https://github.com/gorilla-devs/ferium#check-overrides) for help on that. Please do post the error message next time!
