### ISSUE TITLE
Can't select Mod Loader

### ISSUE THREAD

**Issue by MIPOHBOPOHIH** [gorilla-devs/ferium#236]
## Description
What is the bug?
When I try to select a modaloader, it's just impossible, because neither the enter nor the keyboard just doesn't work

## To Reproduce
What did you do to encounter this bug?
ferium prodile create -> no -> 1.19.2 

## Software version
- OS (**Windows**)
- Ferium Version (**Ferium 4.2.2**)

## Additional information

https://user-images.githubusercontent.com/98014624/202981239-4898d095-3241-4752-9baa-cc506edd6dcc.mp4

**Comment by theRookieCoder** [comment]
You're supposed to use the arrow keys just like the previous version selector. The version selector has a cursor because it defaults to the latest version, but the mod loader obviously shouldn't have a default selection.

**Comment by danielwerg** [comment]
I had to use `j` and `k`, arrows didn't work. kitty sshed to debian server.

**Comment by MIPOHBOPOHIH** [comment]
uh hi
