### ISSUE TITLE
Auto Import

### ISSUE THREAD

**Issue by MIPOHBOPOHIH** [gorilla-devs/ferium#237]
What are some ways to automatically import mods from .mods?
![Uploading image.png…]()

**Comment by MIPOHBOPOHIH** [comment]
![image](https://user-images.githubusercontent.com/98014624/203401933-2a758bb4-a644-4ce5-8f51-1e455029a654.png)

**Comment by theRookieCoder** [comment]
Duplicate of #57

Unfortunately there is no solution as of now
