### ISSUE TITLE
why is gui only for arch???

### ISSUE THREAD

**Issue by dpe0** [gorilla-devs/ferium#238]
why is gui only for arch???

**Comment by theRookieCoder** [comment]
Sorry I don't get it? All distros should have the GUI file picker unless you download the no-gui versions

**Comment by dpe0** [comment]
> Sorry I don't get it? All distros should have the GUI file picker unless you download the no-gui versions

how do i download the gui versions

**Comment by JustSimplyKyle** [comment]
https://github.com/gorilla-devs/ferium/releases/download/v4.2.2/ferium-linux.zip
The download without the prefix is the gui version

**Comment by dpe0** [comment]
> https://github.com/gorilla-devs/ferium/releases/download/v4.2.2/ferium-linux.zip The download without the prefix is the gui version

what about windows?

**Comment by theRookieCoder** [comment]
There is no need to (compatibility wise) because almost all windows instances will have a GUI

**Comment by dpe0** [comment]
> There is no need to (compatibility wise) because almost all windows instances will have a GUI

how do i enable gui? the mod page says nothing about that (i downloaded [ferium-windows-msvc.zip](https://github.com/gorilla-devs/ferium/releases/download/v4.2.2/ferium-windows-msvc.zip))

**Comment by JustSimplyKyle** [comment]
In case you don't understand,the gui version doesn't mean that ferium itself is going to have a gui.
It just means that it enables the functionality of opening a gui file dialogue in linux
Since there's no windows without a gui, that separation is not needed on windows.
