### ISSUE TITLE
if i copy ferium into a different folder will it use a new config?

### ISSUE THREAD

**Issue by dpe0** [gorilla-devs/ferium#240]
the main page says
> "Ferium stores profile and modpack information in its config file. By default it is located at ~/.config/ferium/config.json" 

I can't find that location, so I would like to know where it is. Will it be the same if I move ferium? Or can I use different profiles this way, by just having different feriums in each profile folder

**Comment by theRookieCoder** [comment]
> I can't find that location

Because the directory is in `.config`, it would be hidden by default in most file explorers. You can find instructions for viewing dot directories.

Yes this config file only depends on the username, moving the executable doesn't matter, you can run the ferium binary from anywhere you want and the default config file location will remain the same.

> different feriums in each profile folder

If you want to do this, you need to setup a ferium config file in the directory, and tell ferium to load that config file by using the `$FERIUM_CONFIG_FILE` env var. You can even automatically load this env var whenever you enter the directory using [direnv](https://direnv.net/).

**Comment by dpe0** [comment]
> > I can't find that location
> 
> Because the directory is in `.config`, it would be hidden by default in most file explorers. You can find instructions for viewing dot directories.
> 
> Yes this config file only depends on the username, moving the executable doesn't matter, you can run the ferium binary from anywhere you want and the default config file location will remain the same.
> 
> > different feriums in each profile folder
> 
> If you want to do this, you need to setup a ferium config file in the directory, and tell ferium to load that config file by using the `$FERIUM_CONFIG_FILE` env var (or the `--config-file` flag). You can even automatically load this env var whenever you enter the directory using [direnv](https://direnv.net/). (see [my modpack](https://github.com/theRookieCoder/Kupfur) for an example)

what does ~ mean? i thought it means it will be next to the exe and I do have hidden folders enabled. But how can it be the same for all locations then?

**Comment by theRookieCoder** [comment]
`~` refers to the current users home directory.

**Comment by dpe0** [comment]
> 

how do i do --config-file on windows

**Comment by theRookieCoder** [comment]
You can use `setx FERIUM_CONFIG_FILE "path/to/config/file"` on powershell

**Comment by dpe0** [comment]
> You can use `setx FERIUM_CONFIG_FILE "path/to/config/file"` on powershell

can I do that for only one ferium? it would be very convenient because I have a copy of ferium in each modpack folder and i could just open cmd in that folder without having to worry about downloading mods to wrong modpack

**Comment by theRookieCoder** [comment]
Yes! As I said, you can use [direnv](https://direnv.net/) to load a different config file depending on which folder you're in.

**Comment by dpe0** [comment]
> Yes! As I said, you can use [direnv](https://direnv.net/) to load a different config file depending on which folder you're in.
isn't that linux only? The --config-file thing, can I add it to a windows shortcut as a launch argument? I would try but I don't want to mess my modpacks
