### ISSUE TITLE
Removing mods via cli result in error

### ISSUE THREAD

**Issue by CatGamer23** [gorilla-devs/ferium#241]
## Description
When removing a mod with a Curse ID, Modrinth ID, or Github repo, results in a "Mod X is not in current profile"

## To Reproduce
ran `ferium remove ID`

## Software version
- Windows 10
- Ferium v4.2.2

## Additional information
In order to remove a mod, I have to manually edit the config.json

**Comment by theRookieCoder** [comment]
You're supposed to enter the name
