### ISSUE TITLE
Some small tweaks to the CLI structure

### ISSUE THREAD

**Issue by theRookieCoder** [gorilla-devs/ferium#250]
## The problem

There are some things about the CLI navigation that is probably a little abrupt/jarring for new users, or just isn't intuitive.

## My solutions

@T3sT3ro has some excellent suggestions, detailed in #242

- [ ] When `ferium add` fails, link to documentation about overrides (<https://github.com/gorilla-devs/ferium#check-overrides>) as part of the error message
- [x] `ferium profile` should print the current profile, then <code>Run `ferium profile -h` for more info about this command</code> (likewise for `ferium modpack` too)
- [x] `ferium list` should print a header with information about the profile about to be listed (i.e. profile name, loader, and mc version) as well
- [x] `ferium profile switch` should print more info about the profiles, not just the names (likewise for `ferium modpack switch` too)
- [x] `ferium profiles` should be an alias to `ferium profile list` (likewise for `ferium modpacks` too)
- [x] `ferium mods` should be an alias to `ferium list`
- [x] `ferium info` should show information about the current profile and modpack
- [x] `ferium remove` should print the project id of the removed mods too

**Comment by theRookieCoder** [comment]
Please let me know what you think about these, and if they would be beneficial to your workflows!

**Comment by T3sT3ro** [comment]
Today I thought of one more improvement:
- from the above suggestion instead of `ferium info` use `ferium status` to show currently active profile and modpack
- instead use `ferium info [mods...]` to display the long info about the mod (the same info that is displayed with `ferium list --verbose` but for specified mods only.

**Comment by DeusFerrariis** [comment]
This might just be a curiosity but given #266 as well as the current implementation of remove calling the interactive mode if the provided names arent available, would it be unreasonable to separate methods of specifying mods to remove into seperate commands.  
- It May benefit the design of remove as well as give the user fine tuned control over the remove command. 
- As far as scripted calls to remove it would be nice to avoid interactive sessions when I don't need them

For example 
- `ferium remove --by-id [mod_ids...]`
- `ferium remove --by-name [mod_names]`
- `ferium remove --interactive`

While it would require some restructuring of remove I'd be more than glad to pr that implementation to get some feedback.

**Comment by T3sT3ro** [comment]
Hmm, maybe it's possible to detect when ferium is running in the interactive shell and when not, and abused on that disable interactivity 🤔 maybe check if output is redirected to stdout? I am not sure how to do that in rust but atty in bash does something like that. Anyhow, I think it would be better to have a separate issue for this.
