### ISSUE TITLE
Renaming Jars

### ISSUE THREAD

**Issue by Imzxhir** [gorilla-devs/ferium#252]
## The problem
Is your feature request related to a problem? Please describe it.

It's kinda a problem. Whenever I rename the jar to something like Alternate-EntityCulling and run 'ferium upgrade', it will always go back to the original name 'entityculling-fabric-1.5.2-mc1.19.3' which I find annoying.

## My solutions
Describe any number of solutions you've thought of.

The solution I have thought of is that maybe it would update the mod to the updated version then rename it to what you orginally named it to rather than the name changing to what the updated jar name is.

**Comment by theRookieCoder** [comment]
Could be an addition to #140

Keeping the custom name after a mod upgrade would require #115 to be implemented
