### ISSUE TITLE
error decoding response body: unknown variant `unknown`, expected one of `required`, `optional`, `unsupported` at line 1 column 1888

### ISSUE THREAD

**Issue by SettingDust** [gorilla-devs/ferium#255]
## Description
```
ferium add dark-mode-everywhere-fabric
Adding mod... error decoding response body: unknown variant `unknown`, expected one of `required`, `optional`, `unsupported` at line 1 column 1888
```

## To Reproduce
`ferium add dark-mode-everywhere-fabric`

## Software version
- Windows
- Ferium Version : 4.3.2

**Comment by theRookieCoder** [comment]
This is a bug on Modrinth's side, this variant isn't supposed to exist on listed mods. I recommend manually adding the mod to your `config.json` for now until it gets fixed.
