### ISSUE TITLE
Connection between mod and it's required dependencies

### ISSUE THREAD

**Issue by Tomasan7** [gorilla-devs/ferium#258]
## The problem
When ferium downlaods a mod, it also downloads its required dependencies along with it. When you later remove that mod, the dependencies stay in there, thus leaving "trash" behind, since you do not need those mods.

## My solutions
There would be some kind of connection between mods and their required dependencies. (keep in mind, that the dependencies probably can have dependencies) For exampe, each mod would also save it's required dependencies. When you remove a mod, ferium would look whether it's required dependencies are used only by this mod (because there could be more mods depending on the same dependencies) and if so, remove them as well. It could also be somehow represented in the ui, so you know which mods are dependencies of which.

**Comment by theRookieCoder** [comment]
My current plan is that required dependencies should only be downloaded during upgrading, and shouldn't just be added to the mod list (#99). This completely sidesteps your described problem and has a lot of advantages over the current system, not to mention it's _much_ easier to implement compared to keeping note of mods' dependencies.

As for optional dependencies, they're most likely recommending other mods, so even if you remove the initial mod, I would assume most of the time you want to keep the optional dependency. Anyways your issue isn't about that, and we can deal with it later if someone ever finds optional dependencies a problem.

**Comment by Tomasan7** [comment]
Totally agree, your your solution is much better. As for the optional dependencies, I agree as well, you mostly want to keep them, or if not, it's much easier to find or have a control over.
