### ISSUE TITLE
Downloading outdated version of a mod.

### ISSUE THREAD

**Issue by BalkrishanSingh** [gorilla-devs/ferium#264]
## Description
Downloading JER Integration, Project Id 506948 for 1.18.2 leads to downloading 3.3.1 while 3.3.2 for 1.18.2 exists. It fixes a crash causing bug thats why i even noticed this was outdated. idk if it repeats for any other mod i have.

## To Reproduce
Added the mod and when upgrading it downloads v3.3.1

## Software version
- OS (macOS)
- Ferium Version (4.3.4)

## Additional information
<img width="536" alt="Screen Shot 2023-01-15 at 20 19 58" src="https://user-images.githubusercontent.com/93041640/212548155-073979f9-b0c4-411d-89bf-b49b061ca1d0.png">

<img width="1033" alt="Screen Shot 2023-01-15 at 20 20 38" src="https://user-images.githubusercontent.com/93041640/212548193-e9a36ebf-654f-44db-a20e-654ae86ca037.png">

**Comment by theRookieCoder** [comment]
The author seems to have not properly flagged [this file](https://www.curseforge.com/minecraft/mc-mods/jer-integration/files/3943203) for Forge. I would recommend letting the author know about this, and overriding the mod loader check for now.
