### ISSUE TITLE
Modpack add doesn't download modpack version related to profile version

### ISSUE THREAD

**Issue by BilElSicario** [gorilla-devs/ferium#265]
## Description
Modpack add doesn't download modpack version related to the profile's version, I'm on 1.19.2, profile is on 1.19.2 and installed modpack is 1.19.3. 

## To Reproduce
`ferium modpack add 396246` (Modpack is Fabulously Optimized)
 Would like to create a backup? ` n`
Should overrides be installed? `n`
`ferium modpack upgrade`

## Software version
- OS macOs
- Ferium Version 4.3.4

**Comment by theRookieCoder** [comment]
Your modpacks and profiles are completely unrelated to each other.
#82 should allow you to select a specific version of a modpack, and #94 should allow you to import the mods in a modpack to a profile.
