### ISSUE TITLE
Allow removal of mods using their project IDs too

### ISSUE THREAD

**Issue by theRookieCoder** [gorilla-devs/ferium#266]
## The problem

A lot of new users might find it jarring that mods can't be removed by their IDs, only by their names.

## My solutions

It should be simple to just support both methods simultaneously.

**Comment by DeusFerrariis** [comment]
I'd be interested in implementing this if its up for grabs.

**Comment by theRookieCoder** [comment]
It's actually really simple, you just have to add an additional comparison to check if the input provided is a project's ID
https://github.com/gorilla-devs/ferium/blob/a3362882cc4e73c2ea0850a2fa296d7120642473/src/subcommands/remove.rs#L27
