### ISSUE TITLE
The application is not working

### ISSUE THREAD

**Issue by Bravleubiytsabotov2013** [gorilla-devs/ferium#267]
The app crashes immediately.
I read the instructions, installed and nothing works.
My operating system is Windows 10 Pro version 21H2.
I don’t understand what the problem is, maybe I didn’t install this application correctly, but the instructions seemed to say that the application does not require the installation of any additional software.

**Comment by theRookieCoder** [comment]
This isn't a regular application with a GUI, it's a CLI which is a program that's used in the terminal, i.e. command prompt. If you prefer a GUI, I can recommend prism launcher for updating mods.
