### ISSUE TITLE
Support custom proxies

### ISSUE THREAD

**Issue by ChromaPIE** [gorilla-devs/ferium#276]
## Description
Being in China mainland, I've been haunted by the `Checking internet connection... × Ferium requires an internet connection to work`. I got my v2rayN proxy on, but ferium has simply been kept out of a normal connection. For scoop I can resolve the connection problem just by `scoop config proxy` plus 127.0.0.1 plus the port v2rayN shows for the system proxy. But I don't know how to make ferium work through it.

## To Reproduce
- Move to China
- Sign up for a college and connect your device to the Internet it provides. Ferium worked perfectly with the Internet connection at home, but at my college it's haunted. I'm no pro so I'm confused.
- Execute `ferium upgrade` or any other commands that triggers the Intenet validation check
- Voila.

## Software version
- OS: Windows
- Ferium Version: 4.3.4

**Comment by theRookieCoder** [comment]
Hmm I actually have the same issues, but it only happens on my phone which is really confusing.

Also can't you configure system-wide proxies? Is it really necessary for programs to separately provide proxy functionality?

**Comment by ChromaPIE** [comment]
I've already tried adding and setting `http_proxy` and `https_proxy` in the environment variables, which was said to be able to make CLI programs use proxy, but it just refuses to work. I take Clash for Windows as a temp solution for this for now but it's still quite unstable, failing to connect occasionally, and Clash once messed up the DNS so it's kinda risky. It surely would be better for Ferium to have its own customizable proxy setting but if it's thought to be redundant that's okay.

**Comment by ChromaPIE** [comment]
So the thing is, It do works with Clash on, but it will always start _checking internet connection_ and give _Ferium requires an internet connection to work_ when you let it stay idle for like 30s or so. I don't know how to make an exact description but you can simply imagine a stoned bank teller that you have to yell at em twice to manage to keep the whole business going. There should be something wrong here but I have zero idea.

**Comment by ChromaPIE** [comment]
problems gone for good. closing it
