### ISSUE TITLE
Add option to add mod as soon as its compatible

### ISSUE THREAD

**Issue by otter501** [gorilla-devs/ferium#278]
## The problem
Some mods I want to use aren't on my version so I have to wait until they are, the problem is that I have to either find out manually or edit the config and have an error whenever I update,

## My solutions
Add a parameter like --queue or something like that.

**Comment by theRookieCoder** [comment]
Duplicate of #142

Btw it's normal to leave uncompatible mods in your profile since them not resolving doesn't actually affect other mods downloading.
