### ISSUE TITLE
Command to download a single mod or batch of mods

### ISSUE THREAD

**Issue by owosoup** [gorilla-devs/ferium#280]
## The problem
- When adding a single mod, ferium force-checks my entire folder, even if I just ran `ferium upgrade` before, to add a single mod or two, which can be really unforgiving on old/slow machines like low-cost servers

## My solutions

- Instead of having to update your whole folder, have a command download a list of mods of your choosing
i.e. `ferium download <mod ID>,<mod ID>,<mod ID>,<mod ID>`

**Comment by theRookieCoder** [comment]
Duplicate of #163
