### ISSUE TITLE
Can't run ferium.exe no matter what

### ISSUE THREAD

**Issue by HeavenlyDemon100** [gorilla-devs/ferium#282]
## Description
When trying to open the program it will shut itself immediately and won't open.

## To Reproduce
I just tried to open the program after installing it for the first time.

## Software version
- Windows
- 4.3.4

## Additional information
The problem occurs both when installing from the msvc GitHub release as well as from Scoop.

**Comment by theRookieCoder** [comment]
This application is a CLI, it's meant to be used in a terminal like command prompt or poweshell. If you're not used to CLIs it's pretty difficult to start using ferium. I think [Prism](https://prismlauncher.org) has the ability to update mods too, you can give that a try.
