### ISSUE TITLE
`ferium remove` not working

### ISSUE THREAD

**Issue by IEATDIRTWASNTAVAILABLE** [gorilla-devs/ferium#288]
## Description
`ferium remove` doesn't work at all

## To Reproduce
I run ferium remove and type the mod name in manually, or I run ferium remove and use the fancy gui that pops up

## Software version
MacOS 13.2.1, M1 Mac Mini, using the version of Ferium on homebrew
4.3.4
## Additional information
using `ferium remove` just doesn't work, it doesn't remove the mod from config.json in [username]/.config/ferium, running ferium upgrade doesn't remove it, no matter what mod it's trying to remove

**Comment by theRookieCoder** [comment]
What error do you see? Any changes the program made to your config file will not be saved if it errors out.

**Comment by JakeDevs** [comment]
Having the same issue. I couldn't get a mod from its remote so I removed it but it wasn't working. Ended up manually removing it from the config file.

**Comment by theRookieCoder** [comment]
A quick reminder that when removing mods using the interactive selector, you have to **_press spacebar_** to actually pick the mods to remove then **_press enter_** to actually confirm the selection.

When passing in mods from the CLI you have to make sure you **_escape the spaces_** in the mod name, by using quotes or backslashes. I understand that having to use the mod name isn't intuitive and a fix for #266 will be coming very soon.

**Comment by IEATDIRTWASNTAVAILABLE** [comment]
> What error do you see? Any changes the program made to your config file will not be saved if it errors out.

I dont get any errors at all, and I did not know that you have to press space to select the mods with the GUI, but doing `ferium remove [mod name]` doesn't work either, i'm assuming by the issue being closed that i'm not going to get help with this anymore, i'm not really an expert with github.
I'll try using space in the fancy menu and see if that gets me anywhere, if not, removing the mod from .config and my mods folder isn't that hard

**Comment by theRookieCoder** [comment]
> but doing ferium remove [mod name] doesn't work either

If the mod name has spaces, makes sure you place a backslash before the spaces, on enclose the name in quotes. This is because you can remove multiple mods using the CLI command too. I'm not sure why you aren't getting any errors though, because even a single non-matching mod name will throw an error and won't remove any other mods.

**Comment by theRookieCoder** [comment]
> I'm assuming by the issue being closed that i'm not going to get help with this anymore

Don't worry about that, I closed it because it's not actually a bug as this is after all a bug tracker. You can continue commenting in the issue after it is closed. (you can even reopen it after the fact!)

**Comment by IEATDIRTWASNTAVAILABLE** [comment]
Sorry for not responding for a bit, but pressing space in the "fancy" menu that opens and then pressing enter worked fine.
