### ISSUE TITLE
Missing field `latestEarlyAccessFilesIndexes` in CurseForge API

### ISSUE THREAD

**Issue by error0rre** [gorilla-devs/ferium#290]
## Description
Idk what is the bug and why it happens
## To Reproduce
Try add mod to profile
## Software version
- OS Windows 10 v.1909
- Ferium Version 4.3.4

## Additional information
When i try to add mod(and no matter what mod) from curseforge(i haven't tried modrinth) to profile it's give this error: 

> error decoding response body: unknown field `latestEarlyAccessFilesIndexes`, expected one of `id`, `gameId`, `name`, `slug`, `links`, `summary`, `status`, `downloadCount`, `isFeatured`, `primaryCategoryId`, `categories`, `classId`, `authors`, `logo`, `screenshots`, `mainFileId`, `latestFiles`, `latestFilesIndexes`, `dateCreated`, `dateModified`, `dateReleased`, `allowModDistribution`, `gamePopularityRank`, `isAvailable`, `thumbsUpCount` at line 1 column 13253

**Comment by theRookieCoder** [comment]
I've pushed an emergency update to furse because even my CIs were failing. The field isn't even documented on dosc.cursefoge.com 😡

Anyways, if you install using `cargo install ferium` this issue should be fixed, but I'll keep the issue open till the GitHub Release is out.

**Comment by theRookieCoder** [comment]
9f963529037a9c073c832bacb207820a3bc6d584
