### ISSUE TITLE
Modpack upgrade not working with DawnCraft

### ISSUE THREAD

**Issue by MatheusKael** [gorilla-devs/ferium#300]
### Description

I'm trying to download DawnCraft modpack, but when I run `ferium modpack upgrade` it keeps returning me: 

`missing field 'version' at line 1318 column 1`

### Steps to reproduce

1. Run `ferium modpack add 829758`
2. Run `ferium modpack upgrade`

### Operating System

Windows

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

### Additional Information

![image](https://user-images.githubusercontent.com/43392922/230507836-7abe7ffe-e755-48ab-9a41-c61dcc7a1335.png)

**Comment by theRookieCoder** [comment]
It seems the modpack doesn't specify what it's version is in the manifest. I'll let the author know, but I'll also make [the field](https://github.com/gorilla-devs/libium/blob/main/src/modpack/curseforge/structs.rs#L12) nullable in libium since other modpacks might not specify it too.

**Comment by theRookieCoder** [comment]
This has been fixed by the author
