### ISSUE TITLE
To keep un-updated mods in the mods folder

### ISSUE THREAD

**Issue by mlovescoding** [gorilla-devs/ferium#301]
### The Problem

Whenever I use optifabric to run optifine on fabric, I have to add the optifine manually. And every time I upgrade my mods it always puts it in the .old folder.

### Your Solution(s)

What you could do is make mods that are never updated stay in the folder. Or, you could save the file names (if nobody changes them) so if a new mod with the same ID or name overrides it, you delete THAT old one.

**Comment by theRookieCoder** [comment]
Put your mod in the [user folder](https://github.com/gorilla-devs/ferium#external-mods)

**Comment by theRookieCoder** [comment]
Also some advice, don't use optifine on fabric. Many mods are incompatible, and it doesn't perform that well compared to [the alternatives](https://lambdaurora.dev/optifine_alternatives).
