### ISSUE TITLE
add doesn't work with multiple id's

### ISSUE THREAD

**Issue by Dakes** [gorilla-devs/ferium#303]
### Description

`ferium remove id1 id2 id3` will remove all the selected mods. 
However `ferium add id1 id2 id3` will fail with the error `error: unexpected argument 'id2' found`

### Steps to reproduce

Run `ferium add` with more than one mod id of your choice

### Operating System

Linux

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
Duplicate of #175
