### ISSUE TITLE
Scan mods folder and add existing mods to profile

### ISSUE THREAD

**Issue by Grawl** [gorilla-devs/ferium#305]
### The Problem

I have 57 mods in my `/mods` folder

I want to update them

I looking for a tool to automate updating of all these mods

I found Ferium

I have to manually grab ID from each mod to update them using Ferium

### Your Solution(s)

Provide ability to scan mods folder and try to add each of them to Ferium profile

**Comment by theRookieCoder** [comment]
Duplicate of #57
