### ISSUE TITLE
No mod name for errors during mod downloading

### ISSUE THREAD

**Issue by ChromaPIE** [gorilla-devs/ferium#308]
### Description

Ran `ferium upgrade` as usual but ended up getting `The developer of this mod has denied third party applications from downloading it`. Maybe one or more authors of the mods in my current profile have set their projects to deny 3rd-party download after I added them to my profile.

The problem is, Ferium won't show the exact name /or CurseForge/Modrinth ID of the mod(s) and there are 300+ mods inside so I will definitely refuse to investigate.

### Steps to reproduce

Described above.

### Operating System

Windows

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
Well I didn't realise this would be an issue, since the idea is that you'd catch incompatible mods when adding them. I didn't really think of what would happen if it becomes incompatible after adding.

**Comment by ST-DDT** [comment]
I have the same issue.

**Comment by foodornt** [comment]
will this be fixed?

**Comment by TerminalHash** [comment]
This behavior is not observed on version 4.2.0 or low - it will just say that a mod cannot be downloaded, show it and will continue to download. Why doesn't it work like that now?

**Comment by theRookieCoder** [comment]
Hmm yes it does seem to be a recent regression

**Comment by Nycto97** [comment]
I encountered this issue today as well for the 1st time and starting from now on I'm unable to update any mod in this profile with Ferium. I have close to 500 mods in my Ferium profile so there's no way I'm manually going to find out what mod changed its settings.

**Comment by Nycto97** [comment]
I will try downgrading from 4.4.1 to 4.2.2 as @TerminalHash says the problem doesn't occur on that version.

**Comment by theRookieCoder** [comment]
This seems to have been caused by bad code organisation. In fact, I was able to remove a lot of useless code too when refactoring.
