### ISSUE TITLE
Check if it is possible to port to a newer mc version

### ISSUE THREAD

**Issue by ImsilverDev** [gorilla-devs/ferium#311]
### The Problem

So, it could be a feature that checks all of your mods, you input a version, and if all of these mods are available on the version you input, then you have an option to port your modlist to that version, I have a sv that uses ferium and we want to upgrade to a newer mc version but we have a lot of mods so it would take a while to check every single mod, thanks for reading.

**Comment by theRookieCoder** [comment]
you can just change the minecraft version on your profile and upgrade
