### ISSUE TITLE
github mod downloads two jars

### ISSUE THREAD

**Issue by ilobilo** [gorilla-devs/ferium#312]
I added a mod from github releases but it downloads both `mod-version.jar` and `mod-version-dev.jar`. can I configure it to download only the first one?

**Comment by ilobilo** [comment]
probably needs `&& !asset.name.contains("dev")` here: https://github.com/gorilla-devs/libium/blob/0687d0b49f82a0b55b84649b07c1ef4c609ec0af/src/upgrade/check.rs#L59

**Comment by ilobilo** [comment]
I re-upgraded and now it only downloads the dev version

**Comment by theRookieCoder** [comment]
It isn't possible to resolve mods in your situation at the moment (unless you hardcode it in a custom version or something). A feature that would fix your issue is planned, namely [filters](https://github.com/gorilla-devs/ferium/issues/155#issuecomment-1481303888)
