### ISSUE TITLE
ferium upgrade doesn't work

### ISSUE THREAD

**Issue by ipiiia** [gorilla-devs/ferium#313]
### Description

with this message

HTTP status client error (404 Not Found) for url (https://api.modrinth.com/v2/project/AKgnrAFj/version)

### Steps to reproduce

1. run ferium upgrade
2. HTTP status client error (404 Not Found) for url (https://api.modrinth.com/v2/project/AKgnrAFj/version)

### Operating System

macOS

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
Whatever project that was, it has unfortunately been pulled from Modrinth, it might have been reuploaded so I recommend you check for that too.
