### ISSUE TITLE
Will not install through cargo

### ISSUE THREAD

**Issue by bsasealteam6** [gorilla-devs/ferium#314]
### Description

I get the error 
```
cargo install ferium 
    Updating crates.io index
  Downloaded ferium v4.4.0
error: failed to parse manifest at `/home/fortnen2/.cargo/registry/src/github.com-1ecc6299db9ec823/ferium-4.4.0/Cargo.toml`

Caused by:
  invalid type: unit variant, expected string only for key `profile.release.strip`
  ```
whenever I try to install through cargo.

### Steps to reproduce

On Debian 11:
- run `sudo apt install cargo`
- run `cargo install ferium`

### Operating System

Linux

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
Not entirely sure what the issue is, but it’s most likely to do with your rust version. _Never_ install Rust using your package manager, always use rustup
