### ISSUE TITLE
Show verbose listing of mods in alphabetical order

### ISSUE THREAD

**Issue by jokrefta** [gorilla-devs/ferium#315]
### The Problem

`ferium list` shows mods in alphabetical order. However, `ferium list -v` does not. 

### Your Solution(s)

It would be nice to at least have the option of sorting in alphabetical order when doing the verbose listing, or just have it sorted that way by default.

**Comment by khuongduy354** [comment]
Is anyone doing this? If not, let me have a look.

**Comment by theRookieCoder** [comment]
Sorry for leaving you hanging @khuongduy354, I know the list code is a bit of a mess. I'll answer your questions when I take a look at the code and implement this issue.

**Comment by khuongduy354** [comment]
It's ok, take ur time
