### ISSUE TITLE
Downloading for GitHub not working in certain case

### ISSUE THREAD

**Issue by probablypablito** [gorilla-devs/ferium#316]
### Description

I want to download the mod [carpet-autoCraftingTable](https://github.com/gnembon/carpet-autoCraftingTable), which should meet the criteria of having a JAR file available in the releases. Despite this it does not run.

### Steps to reproduce

`ferium add gnembon/carpet-autoCraftingTable`
> Adding mod... The project/repository is not compatible

### Operating System

Linux

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
The project doesn't specify the mod loader, so you have to skip the mod loader check. You can do this by adding the `--dont-check-mod-loader` flag to your add command, i.e. run `ferium add gnembon/carpet-autoCraftingTable --dont-check-mod-loader` to properly add this mod.

**Comment by probablypablito** [comment]
Alright, thank you! Could could that be added to the error message in a future release? No worries if not. I appreciate it!

**Comment by theRookieCoder** [comment]
I'll link to the readme/help page/documentation when I add filters, since they will be more complex (but flexible).
