### ISSUE TITLE
Ferium downloads incorrect version of yet-another-config-lib

### ISSUE THREAD

**Issue by ItsJasperHere** [gorilla-devs/ferium#319]
Ran ` ferium upgrade ` but ferium installs the incorrect version of ` yet-another-config-lib ` and installs the forge one instead of the fabric one. 

Steps to reproduce - 
Not sure but probably add `yet-another-config-lib` to a 1.19.4 profile with Fabric and run `ferium upgrade`. 

OS -
Windows

Yes, I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
<img width="829" alt="Screenshot 2023-05-17 at 4 16 31 PM" src="https://github.com/gorilla-devs/ferium/assets/60034030/8bc3966c-36fb-46e8-879f-16881cb9e083">

Seems to be a fault on the developer's end
