### ISSUE TITLE
Move mod files to backup folder on profile switch (mod caching)

### ISSUE THREAD

**Issue by tippfehlr** [gorilla-devs/ferium#320]
### The Problem

Currently mod files are not removed when switching to another profile (in the same mod directory).
That means manually upgrading is necessary to switch to that profile.
When creating a new empty profile, even upgrading doesn’t remove the mod files.

Also, while not needed mods are placed in .old, they are redownloaded every time when switching back to a profile.

### Your Solution(s)

When switching profiles, move files that belong to a mod into a cache folder associated with ferium. On Linux I would use `~/.cache/ferium/mods/`. (all files that **don’t** belong to a mod can be moved to `.old`)
Next, add the file names to the profile. When switching to a profile, simply *copy* the file into the defined mod folder (copy, because in another mod folder that mod could be needed again).
That way, switching to a profile doesn’t need internet.

When doing an upgrade, check if the older mod file is still needed in another profile. When not, delete it. (don’t check if the mod is still needed when doing a full upgrade)

When a mod is not found in cache, inform the user when run with `--verbose` . Always just redownload the mod.

**Comment by theRookieCoder** [comment]
> switching to another profile (in the same mod directory)

Ferium profiles are meant to be paired with profiles in your launcher. Multiple profiles using the same output directory isn't something I want to explicitly work on supporting.

As for the your solutions, there are already plans for a pnpm-like mod cache in #109

**Comment by tippfehlr** [comment]
> Ferium profiles are meant to be paired with profiles in your launcher. Multiple profiles using the same output directory isn't something I want to explicitly work on supporting.

Gotcha, that makes sense to me. It would be cool to see GDLauncher’s mod support get as good as ferium’s.



> As for the your solutions, there are already plans for a pnpm-like mod cache in #109

Ah sorry I didn’t search for open issues.
