### ISSUE TITLE
`remove` doesn't show which mods are marked for deletion when pressing the space key

### ISSUE THREAD

**Issue by palapapa** [gorilla-devs/ferium#326]
### Description

As per the title, when pressing the space key on the mods to remove, the green checks next to the mods will always stay on.

### Steps to reproduce

Reproducible by trying to press the space key while removing mods.

### Operating System

Windows

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by palapapa** [comment]
I AM using Windows Terminal.

**Comment by theRookieCoder** [comment]
Could you send a screenshot with some mods selected

**Comment by palapapa** [comment]
I just realized they are supposed to be checked only after selecting them. I thought the checks would disappear after I select the mods to remove.
When I use `remove`, all mods are already checked. Selecting some mods change nothing.

**Comment by theRookieCoder** [comment]
> When I use remove, all mods are already checked. Selecting some mods change nothing

Can you send a screenshots or a screen recording of this, I have no idea what's happening unless you show me what you're encountering.

**Comment by palapapa** [comment]
![image](https://github.com/gorilla-devs/ferium/assets/61058728/b55a5092-6efa-42d3-a480-18f671a57204)
