### ISSUE TITLE
Make `--dont-check-game-version` and `--dont-check-mod-loader` apply to dependencies as well

### ISSUE THREAD

**Issue by palapapa** [gorilla-devs/ferium#328]
### The Problem

Right now those two options only apply to the mod you are currently installing, not its dependencies, and can cause some of them to fail to install.

### Your Solution(s)

Make `--dont-check-game-version` and `--dont-check-mod-loader` apply to dependencies as well.

**Comment by theRookieCoder** [comment]
This should be fixed by #175
