### ISSUE TITLE
HTTP status client error (403 Forbidden)

### ISSUE THREAD

**Issue by TinyDerp** [gorilla-devs/ferium#339]
### Description

When I tried to upgrade one of my profiles it gave me this error while determining the latest compatible versions:  `HTTP status client error (403 Forbidden) for url (https://api.curseforge.com/v1/mods/435044/files?pageSize=10000)`
I figured out that it was for a curseforge mod named Better Third Pearson. After removing the mod from my profile list and trying to add it again it gave me the same error in the adding faze (`Adding mod... ←[1;31mHTTP status client error (403 Forbidden) for url (https://api.curseforge.com/v1/mods/435044)←[0m`).
Opening the website that was given in the error on my browser (Opera GX) it gave me an HTTP with the same error code 403.
Is this a curseforge thing or ferium problem I have no clue. This is the first time I have ever seen this error also it did d 
determin two of the mods when I used the upgrade command but those mods where from modrinth.
Additionally it doesn't work with any other curseforge mods either (adding mods I mean).

### Steps to reproduce

1. Use ferium add 123456 (curseforge mod id)
2. Get error

### Operating System

Windows

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

### Additional Information

It might be because curseforge added a 1.20 section in its website already. Not a developer, don't know.

**Comment by equinox** [comment]
Hi, it's actually because of this: https://github.com/gorilla-devs/ferium/discussions/337
If you'd like to read more, there's an evolving document which you can find here: https://hackmd.io/@jaskarth4/B1gaTOaU2
