### ISSUE TITLE
Add support for PrismMC's `.disabled` mods

### ISSUE THREAD

**Issue by JustSimplyKyle** [gorilla-devs/ferium#34]
Currently I'm using ferium witn polymc, and when I'm debugging mods I will often disable mods via polymc. When a mod is disabled, it will add `.disabled` at the end of the mod name. But when I do `ferium upgrade`, it will automatically "enable" the mod again. I want ferium to not touch `.disabled` mods.

**Comment by theRookieCoder** [comment]
But if the mod has an upgrade could it upgrade the disabled mod?

**Comment by KyleUltimate** [comment]
Well I guess no, not until the mod got enabled again in polymc.
The mod loader just ignores mod that doesn't end with .jar`

**Comment by KyleUltimate** [comment]
Or you could still upgrade it, but keep it disabled.
Also, some other launcher will not use `.disabled`, some will use `.old` instead

**Comment by theRookieCoder** [comment]
> Or you could still upgrade it, but keep it disabled

Yup that's what I intended

**Comment by KyleUltimate** [comment]
Hmm, wouldn't it be possible using the current updating method? I *believe* the current updating method is just comparing filenames. If it's that, couldn't you just first ignore the `.disabled` name and only compare the part that doesn't have it?
And after downloading the mod, rename the new mod to have an end with `.disabled`, and delete the "original" .disabled mod

**Comment by theRookieCoder** [comment]
That's what I thought at first. But the problem is that if the old version was disabled, Ferium would just download the new version and end up 'enabling' the mod again :(

**Comment by KyleUltimate** [comment]
Oh I know what you mean! This is quite a nasty problem to solve...
Maybe add a boolean to the config to signifies that the mod is disabled? And when ferium checks for upgrading, if the mod is set disabled in config, just straight up don't touch it

**Comment by theRookieCoder** [comment]
Oh yeah that's possible but it's not quite convenient because you would disabled the mod in polymc and ferium

**Comment by theRookieCoder** [comment]
> This is quite a nasty problem to solve...

I wonder how other mod managers like PolyMC itself deal with this

**Comment by KyleUltimate** [comment]
Couldn't you just auto detect a mod with file extension `.disabled` and auto add it to config?(maybe first ask it when upgrading, smth like (Do you want to disable this mod in Ferium?)
And when got enabled again, ferium could detect that in config, the mod is disabled, but in the folder, it doesn't have the `.disabled` file ending, so ferium enables it in config and upgrades it

**Comment by KyleUltimate** [comment]
> > This is quite a nasty problem to solve...
> 
> I wonder how other mod managers like PolyMC itself deal with this

Well iirc, I don't think PolyMC has auto upgrading, it's a planned feature in 1.3.0, but it has not been implemented

**Comment by theRookieCoder** [comment]
> Couldn't you just auto detect a mod with file extension .disabled and auto add it to config?

**Sigh** same problem again, how would I know what mod was disabled?

**Comment by theRookieCoder** [comment]
> I wonder how other mod managers like PolyMC itself deal with this

But it seems to be able to detect which mods are in the mods directory. If I remove a few mods, it doesn't show those mods in the menu

**Comment by KyleUltimate** [comment]
Well maybe they just don't store it in another config
They just kept checking what mods are in the directory
I could be wrong tho, I don't know how does PolyMC works
And another question, does curseforge api doesn't have hash checking?

**Comment by theRookieCoder** [comment]
> They just kept checking what mods are in the directory

Yup that's what they do. They even parse the mod manifests [here](https://github.com/PolyMC/PolyMC/blob/develop/launcher/minecraft/mod/LocalModParseTask.cpp). It's all C++ though so I don't really know what they're doing.

**Comment by KyleUltimate** [comment]
From my rough reading, it seems like they do read into fabric.mod.json and save things from it

**Comment by KyleUltimate** [comment]
Although it seems like the forge formats are a lot more complicated

**Comment by theRookieCoder** [comment]
Moved to #219

**Comment by ok-coder1** [comment]
Is this fixed? Well now ferium knows which mod is which if you run ferium scan so shouldn't this problem be fixed?
