### ISSUE TITLE
Can't upgrade a profile if it contains Curseforge mods

### ISSUE THREAD

**Issue by slushie0** [gorilla-devs/ferium#341]
### Description

When trying to up upgrade my profile that contains mods from mostly Modrinth and some from Curseforge, it starts checking mod availability but quits as soon as it hits a Curseforge mod with the error:

`HTTP status client error (403 Forbidden) for url (https://api.curseforge.com/v1/mods/386175/files?pageSize=10000)`

My profile had these 4 Curseforge mods:

- https://www.curseforge.com/minecraft/mc-mods/accurate-block-placement
- https://www.curseforge.com/minecraft/mc-mods/effective
- https://www.curseforge.com/minecraft/mc-mods/sheep-consistency
- https://www.curseforge.com/minecraft/mc-mods/worldedit

### Steps to reproduce

1. Run `ferium upgrade` on a profile with Curseforge mods. The mods I had are listed above.
2. Error appears

### Operating System

Windows

### Are you using the latest version of ferium?

- [x] I am using the latest version of ferium

### Additional Information

![image](https://github.com/gorilla-devs/ferium/assets/57730247/d6341063-9bba-4e99-bce4-a151e639a2e9)

**Comment by equinox** [comment]
You'll want to take a look at this discussions post [here](https://github.com/gorilla-devs/ferium/discussions/337) that explains ferium specific context as to why this is happening, and also probably take a look at [this github repo's readme](https://github.com/fractureiser-investigation/fractureiser/blob/main/README.md) for a wider explaination of what's happening over the last few days.
