### ISSUE TITLE
itsmeow/BetterTridentReturn on GitHub Releases doesn't work as expected

### ISSUE THREAD

**Issue by IllusoryZephyr** [gorilla-devs/ferium#343]
### Description

a lot of mods from github is incompatible with the use of ferium. such as jaredlll08 mods and itsmeow/BetterTridentReturn.

### Steps to reproduce

1. Run "ferium add itsmeow/BetterTridentReturn"
2.  Shows mod incompatible even when using the available versions

### Operating System

Windows

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by equinox** [comment]
What version of MineCraft are you trying to add these mods to? Can you also specify some of the jaredlll08 mods that you experience this with?

**Comment by IllusoryZephyr** [comment]
> What version of MineCraft are you trying to add these mods to? Can you also specify some of the jaredlll08 mods that you experience this with?

The versions that I've tried (for some mods): 1.18.2, 1.19, 1.19.2, 1.19.3, 1.19.4
All jaredlll08 mods including Controlling For Fabric, also including all maruohon mods like Malilib, MiniHUD and Litematica

**Comment by theRookieCoder** [comment]
I checked BetterTridentReturn and even though I'd expect it to work, it doesn't seem to. I will investigate this.

None of Jared's or Matti's mods seem to have any releases?

**Comment by IllusoryZephyr** [comment]
> I checked BetterTridentReturn and even though I'd expect it to work, it doesn't seem to. I will investigate this.
> 
> None of Jared's or Matti's mods seem to have any releases?

Oh, so it needs releases. 

What about curseforge? Why is it not working?

Is it possible to automatically compile and install mods from GitHub?

**Comment by theRookieCoder** [comment]
> What about curseforge? Why is it not working?

See #337 for context, the TLDR is you need to set the `CURSEFORGE_API_KEY` env var to `$2a$10$sI.yRk4h4R49XYF94IIijOrO4i3W3dAFZ4ssOlNE10GYrDhc2j8K.`, something like `export CURSEFORGE_API_KEY='$2a$10$sI.yRk4h4R49XYF94IIijOrO4i3W3dAFZ4ssOlNE10GYrDhc2j8K.'` should work on bash/zsh.

> Is it possible to automatically compile and install mods from GitHub?

I do plan on adding this eventually. It's actually what started this project in the first place, but I eventually decided it was too difficult.

**Comment by IllusoryZephyr** [comment]
> > What about curseforge? Why is it not working?
> 
> See #337 for context, the TLDR is you need to set the `CURSEFORGE_API_KEY` env var to `$2a$10$sI.yRk4h4R49XYF94IIijOrO4i3W3dAFZ4ssOlNE10GYrDhc2j8K.`, something like `export CURSEFORGE_API_KEY='$2a$10$sI.yRk4h4R49XYF94IIijOrO4i3W3dAFZ4ssOlNE10GYrDhc2j8K.'` should work on bash/zsh. (you won't need this anymore after I release the next update)
> 
> > Is it possible to automatically compile and install mods from GitHub?
> 
> I do plan on adding this eventually. It's actually what started this project in the first place, but I eventually decided it was too difficult.

Ohh, I don't have much experience with coding so I can't comment much 😅, good luck to you though.

Thank you for the help!
