### ISSUE TITLE
Can't add/download mods from curseforge

### ISSUE THREAD

**Issue by 432533** [gorilla-devs/ferium#350]
### Description

An error is displayed
HTTP status client error (403 Forbidden) for url (https://api.curseforge.com/v1/mods/225608)
Ferium version 4.4.0

### Steps to reproduce

./ferium add (mod id)
./ferium upgrade 

### Operating System

Windows

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by msfjarvis** [comment]
https://github.com/gorilla-devs/ferium/discussions/337#discussioncomment-6111930
