### ISSUE TITLE
HTTP status client error (403) when trying to add Curseforge mods to a profile

### ISSUE THREAD

**Issue by NorthernMagic** [gorilla-devs/ferium#355]
### Description

Whenever I run `ferium add <curseforge_project_id>` it returns an HTTP status client error, blocking me from adding the mod to the profile. Mods hosted on Modrinth still add successfully, but this is a problem for me when the mod I'm looking for is hosted exclusively on Curseforge.

![image](https://github.com/gorilla-devs/ferium/assets/116324840/e22d2a0d-4461-41c6-90d1-d849cf22f3d3)

### Steps to reproduce

To reproduce:

1.  Open Windows Terminal
2.  Add a mod from a project hosted on Curseforge

### Operating System

Windows

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by Kaz-49** [comment]
Try doing `ferium add --curseforge-api-key '$2a$10$sI.yRk4h4R49XYF94IIijOrO4i3W3dAFZ4ssOlNE10GYrDhc2j8K.' <curseforge_project_id>`

I'm pretty sure it had something to do with the forge virus thing that's been happening, but I might be remembering wrong. Hopefully soon all this virus stuff will get ironed out and we can just use the command without the big key in the middle :)

[Reference back](https://github.com/gorilla-devs/ferium/issues/349#issuecomment-1600550535)

**Comment by DlljsCodes** [comment]
> Try doing `ferium add --curseforge-api-key '$2a$10$sI.yRk4h4R49XYF94IIijOrO4i3W3dAFZ4ssOlNE10GYrDhc2j8K.' <curseforge_project_id>`
> 
> I'm pretty sure it had something to do with the forge virus thing that's been happening, but I might be remembering wrong. Hopefully soon all this virus stuff will get ironed out and we can just use the command without the big key in the middle :)
> 
> [Reference back](https://github.com/gorilla-devs/ferium/issues/349#issuecomment-1600550535)

This command, as well as, `ferium --curseforge-api-key '$2a$10$sI.yRk4h4R49XYF94IIijOrO4i3W3dAFZ4ssOlNE10GYrDhc2j8K.' add <curseforge_project_id>` don't work. Maybe that API key has expired or the v1 API is down.

You might be able to create an API key on the CurseForge website for yourself and use that.

**Comment by theRookieCoder** [comment]
> Try doing `ferium add --curseforge-api-key '$2a$10$sI.yRk4h4R49XYF94IIijOrO4i3W3dAFZ4ssOlNE10GYrDhc2j8K.' <curseforge_project_id>`

This wouldn't work since the api key flag has to apply to the root command instead of the subcommand.

> `ferium --curseforge-api-key '$2a$10$sI.yRk4h4R49XYF94IIijOrO4i3W3dAFZ4ssOlNE10GYrDhc2j8K.' add <curseforge_project_id>` don't work.

This command does work, I have just checked.
