### ISSUE TITLE
Automatically (or with a flag) switch the mods in the mod folder when changing profiles.

### ISSUE THREAD

**Issue by K4LCIFER** [gorilla-devs/ferium#356]
### The Problem

When switching profiles, I have to manually upgrade each time so that the mods switch.

### Your Solution(s)

It would be nice if the mods got automatically changed to the specific profile's mods when changing profiles.

**Comment by theRookieCoder** [comment]
The idea is that you'd link your profile output directories to separate launcher profiles with separate instance directories, i.e. you'd never have two profiles output to the same directory. But I understand that that use case also makes sense so #333 should solve that.
