### ISSUE TITLE
Auto Switch to profile

### ISSUE THREAD

**Issue by redstonerti** [gorilla-devs/ferium#358]
### The Problem

I am not sure if there is a way to do this. If there is, please tell me and i'll close the issue, but is it possible to make use a bash script to automatically switch to a specific profile? Because the menu complicates things a bit.

### Your Solution(s)

Create a way to switch profile without the menu.

**Comment by theRookieCoder** [comment]
You can specify the name of the profile to switch to as an argument, i.e. `ferium profile switch <profile_name>`. You can run `ferium profile switch --help` for more info.

**Comment by redstonerti** [comment]
thanks!
