### ISSUE TITLE
"os error 2" on doing "ferium modpack upgrade"

### ISSUE THREAD

**Issue by thecountrox** [gorilla-devs/ferium#360]
### Description

Ferium installs a few mods but then promptly stops saying "os error 2 "
Platform : linux

### Steps to reproduce

Run `ferium modpack modpackid`
`ferium modpack upgrade`

### Operating System

Linux

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
Could I have the ID of the modpack that made you get this error?

**Comment by theRookieCoder** [comment]
@thecountrox could I please have the ID of the modpack you used that made you get this error? It is impossible for me to figure out anything without it.
