### ISSUE TITLE
i can't add mods from curseforge

### ISSUE THREAD

**Issue by VinixChan** [gorilla-devs/ferium#361]
### Description

when i try add some mod from curseforge, his show me that error:
**HTTP status client error (403 Forbidden) for url (https://api.curseforge.com/v1/mods/225608)**

### Steps to reproduce

open cmd / terminal
ferium add **mod id**
error
![imagem_2023-07-20_135919274](https://github.com/gorilla-devs/ferium/assets/94625459/01e37d54-3e9a-4ab3-85ed-463d036f6297)

### Operating System

Windows

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by sharkman** [comment]
The same error during "ferium upgrade" command, probably curseforge blocking api access.
![image](https://github.com/gorilla-devs/ferium/assets/113660/d0c63f14-a72a-46da-b0b9-80ff382917df)

**Comment by theRookieCoder** [comment]
Please see [#337](https://github.com/gorilla-devs/ferium/discussions/337#discussioncomment-6111930) for what happened and how to fix your problem
