### ISSUE TITLE
Unable to detect/connect to Internet

### ISSUE THREAD

**Issue by Degenerate-Peanut** [gorilla-devs/ferium#362]
### Description

I had removed Ferium a couple months ago, It was working perfectly, I redownloaded/installed through scoop on my Windows 11 PC (all commands sent through Powershell 7) just yesterday, and upon attempting to create a profile or do anything that requires a connection to the internet, It prints this message (here's an example):

PS C:\Users\<User>/ ferium profile create
Checking internet connection... × Ferium requires an internet connection to work

My home has 2 different Internet providers, so I attempted to run the same command above on each through both wifi and LAN connections, uninstalling and re-installing occasionally, but nothing seemed to work

### Steps to reproduce

1. Install Ferium through scoop
2. Run "_ferium profile create_", "_modpack add_", etc. in powershell or command prompt and watch as it prints an internet connection error message: **_Checking internet connection... × Ferium requires an internet connection to work_**

### Operating System

Windows

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
This should be resolved by #310, I'm unfortunately very busy and can't really do any programming at the moment. If you are able to, disabling the internet check by using an early return on https://github.com/gorilla-devs/ferium/blob/0304b528b4654dfc920ed7105f9e1c2ee8e507a1/src/main.rs#L458 should work
