### ISSUE TITLE
Ferium cannot add mods that support NeoForge from Curseforge

### ISSUE THREAD

**Issue by medsal15** [gorilla-devs/ferium#363]
### Description

Mods that support [NeoForge](https://neoforged.net/) on curseforge cannot be added. Instead ferium gives `error decoding response body: invalid value: 6, expected one of: 0, 1, 2, 3, 4, 5 at line 1 column 4561`.

An example of such mods is [Gateways to Eternity](https://www.curseforge.com/minecraft/mc-mods/gateways-to-eternity)

### Steps to reproduce

- Run `ferium add 417802` (or any other NeoForge mod)
- Ferium returns `error decoding response body: invalid value: 6, expected one of: 0, 1, 2, 3, 4, 5 at line 1 column 4561` and the mod is not added

### Operating System

Windows

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by CrazyWolf13** [comment]
Can confirm
