### ISSUE TITLE
'error decoding response body' for certain Curseforge mods

### ISSUE THREAD

**Issue by brianfreud** [gorilla-devs/ferium#364]
### Description

Certain mods are throwing this error:
"Adding mod... error decoding response body: invalid value: 6, expected one of: 0, 1, 2, 3, 4, 5 at line 1 column 5496" - mod 374492

"Adding mod... error decoding response body: invalid value: 6, expected one of: 0, 1, 2, 3, 4, 5 at line 1 column 10564" - mod 223852

"Adding mod... error decoding response body: invalid value: 6, expected one of: 0, 1, 2, 3, 4, 5 at line 1 column 5940" - mod 511733

### Steps to reproduce

1. Run ferium add ####
2. Get error

### Operating System

Linux

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

### Additional Information

Tested with version 4.4.0.

**Comment by theRookieCoder** [comment]
The latest version v4.4.1 fixes this
