### ISSUE TITLE
Add option to hide donation message

### ISSUE THREAD

**Issue by ItsProfessional** [gorilla-devs/ferium#369]
### The Problem

When adding a mod or modpack, and the author has a donation link, ferium tells the user to consider donating to the author.
This isn't a problem when installing mods normally, but when mass installing tons of mods using a script, it clutters up the output.

For example, this:
```sh
ferium add x && ferium add y && ferium add z && ferium add a && ferium add b && ferium add c
```

results in this output:
```yaml
Adding mod... ✓ x
Consider supporting the mod creator on X (https://paypal.me/author)
Adding mod... ✓ y
Consider supporting the mod creator on X (https://paypal.me/author)
Adding mod... ✓ z
Consider supporting the mod creator on X (https://paypal.me/author)
Adding mod... ✓ a
Consider supporting the mod creator on X (https://paypal.me/author)
Adding mod... ✓ b
Consider supporting the mod creator on X (https://paypal.me/author)
Adding mod... ✓ c
Consider supporting the mod creator on X (https://paypal.me/author)
```

### Your Solution(s)

Add a flag like `--hide-donation-message` that suppresses the donation message.

**Comment by ok-coder1** [comment]
Close this, because donation messages were entirely removed in #400.

**Comment by theRookieCoder** [comment]
Donation messages were removed in 40a1043c92e98abc54e7b9d8ae138058f8c7f76e when adding multiple mods was implemented.
