### ISSUE TITLE
Ferium doesn't work with modrinth anymore (ERR 404)

### ISSUE THREAD

**Issue by boingtheboeing** [gorilla-devs/ferium#372]
### Description

When I try to add any modrinth mod it gives me a 404 Error 

Example:
<img width="770" alt="image" src="https://github.com/gorilla-devs/ferium/assets/76058130/e4586571-8637-4642-a7ea-eb738dc41391">

### Steps to reproduce

1. Start ferium
2. Add any modrinth mod

### Operating System

other (Specify in Additional Information)

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

### Additional Information

Doesn't work on any os (tested Linux and Windows)

**Comment by theRookieCoder** [comment]
Other Modrinth mods work fine, the mod you specified (https://modrinth.com/project/1hGA9TYQ) does not exist or isn't public yet.
