### ISSUE TITLE
Ferium downloads latest quilt-compatible build, ignoring newer builds if they are only fabric-compatible

### ISSUE THREAD

**Issue by ItsProfessional** [gorilla-devs/ferium#373]
### Description

Ferium downloads the latest quilt-tagged build of the mod, instead of looking for either fabric-tagged or quilt-tagged.

This is a problem for a mod such as Fluid Void Fading, because the latest build is tagged as only fabric-compatible. Even though it is backwards compatible with quilt. There prior build is tagged as both fabric and quilt, so ferium chooses to download that instead of the latest build.

### Steps to reproduce

1. Run `ferium add fluidvoidfading`
2. Run `ferium upgrade`
3. Check the version of the downloaded mod

### Operating System

Linux

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

### Additional Information

Fluid Void Fading 1.1.0 supports fabric and quilt natively. But 1.1.2 is only tagged to support fabric. So ferium is downloading the older version that is compatible with quilt, ignore the newer fabric-tagged build. Ferium taking this into account is absurd, since fabric mods are compatible with quilt and there's no reason to check this.

Suggested fix: If the mod loader of the profile is Quilt, then find a build that is available for EITHER fabric or quilt. Don't just look for the latest quilt-compatible build.

[Sodium breaks with any version that is older than 1.1.2](https://github.com/CaffeineMC/sodium-fabric/blob/21385865dbb6ea41f4fa4d202d84e5c6247455a0/src/main/resources/fabric.mod.json#L60C33-L60C33), so currently it is impossible to download this mod along side sodium using ferium.

**Comment by theRookieCoder** [comment]
> Ferium taking this into account is absurd, since fabric mods are compatible with quilt and there's no reason to check this.

> Suggested fix: If the mod loader of the profile is Quilt, then find a build that is available for EITHER fabric or quilt. Don't just look for the latest quilt-compatible build.

This assumes that every fabric mod works perfectly with Quilt. That's what I thought and implemented at first, but I changed that behaviour with #30. You have to consider that it's perfectly possible for an author to publish separate versions for Quilt and Fabric. If the method you suggest was used, ferium could download a version made for Fabric ªthat might be compatible) even if there's another version available that's specifically made for Quilt.

**Comment by theRookieCoder** [comment]
As for this specific case you encountered, I chalk it up to the author making a mistake when marking the compatibility of the version (as was what happened with Iris in #30). It's certainly accidental, and there's no harm in contacting the author and letting them know.
