### ISSUE TITLE
Coudn't download a modpack

### ISSUE THREAD

**Issue by Rider3268** [gorilla-devs/ferium#376]
### Description

When trying to download a modpack, got **"missing field 'version' at line 358 column 1"** error.

### Steps to reproduce

1. Install latest ferium version
2. Run **"ferium modpack add <modpack_id>"**
3. Run **"ferium modpack upgrade"**

### Operating System

Linux

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

### Additional Information

I'm using arch linux, so got ferium from AUR, but according to PKGBUILD this is the latest release version.
Tried to download _Create Optimized_ modpack with id 644155.

**Comment by theRookieCoder** [comment]
It seems the creator of the pack doesn't specify the modpack version in the manifest file, and instead just adds it to the name (which is not the correct format). If you know how to, could you try letting the author know about this issue?
