### ISSUE TITLE
Programming Language Support

### ISSUE THREAD

**Issue by redd-rl** [gorilla-devs/ferium#379]
### The Problem

It'd be cool if Ferium had interfaces/bindings for languages like Python or C, or C++ or whatever, could allow for UI building or automated programs to handle profiles.

### Your Solution(s)

batch files with ferium commands

**Comment by theRookieCoder** [comment]
Ferium uses a closely-tied backend library called [libium](https://github.com/gorilla-devs/libium). Currently the separation of code between the two is quite poor, but nonetheless a lot non-UI related ferium functionality is housed there. Rust code can create C-bindings which almost every language supports. C/C++ interop is not that difficult iirc, and I think there are solutions for calling Rust code from languages like Python too.

**Comment by redd-rl** [comment]
Considering I'm a python dev myself, would the best route not be to set-up py binds from rs then?
