### ISSUE TITLE
Windows, scoop, Running does nothing.

### ISSUE THREAD

**Issue by drakosoldier298** [gorilla-devs/ferium#380]
### Description

i installed through scoop on windows 11 and running the exe brings a command prompt and then nothing

### Steps to reproduce

1 run ferium,
2 see nothing happen.
im sure im doing something wrong.

### Operating System

Windows

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by vanja-san** [comment]
@drakosoldier298 It seems there is no need to launch via executable. Just enter `ferium` command into windows terminal.
Description says:
### Ferium is a fast and feature rich `CLI program`...

**Comment by theRookieCoder** [comment]
Yup, this program is to be used in the command line, it doesn't have a GUI and as such launching the `exe` as you would any other app won't do anything.
