### ISSUE TITLE
To you or not to you?

### ISSUE THREAD

**Issue by vanja-san** [gorilla-devs/ferium#382]
Does this need to be shown to you or to the developer on the mod site? I install the mod with ferium, but the dependencies of this mod are not installed.

![Снимок экрана 2023-11-12 180800](https://github.com/gorilla-devs/ferium/assets/7201687/66bc6997-c5c4-4bc6-96bb-98ee8efbe369)

`Sorry: bad English!`

**Comment by theRookieCoder** [comment]
The mod author should specify this dependency in their project on CurseForge or Modrinth, you should be reporting this to them.
