### ISSUE TITLE
Confirmation prompt gets duplicated sometimes

### ISSUE THREAD

**Issue by vanja-san** [gorilla-devs/ferium#388]
### Description

Just duplicates dependency messages when installing

### Steps to reproduce

Just install [Paladin's Furniture](https://www.curseforge.com/minecraft/mc-mods/paladins-furniture/relations/dependencies) with cursforge

### Operating System

Windows

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

### Additional Information

![Снимок экрана 2023-11-19 221615](https://github.com/gorilla-devs/ferium/assets/7201687/750869eb-3e4f-4a55-a6db-68dc54490283)

**Comment by theRookieCoder** [comment]
Hmm yes I've noticed this a couple of times, and I'm pretty sure it is a bug in dialoguer, I'll have to take a look

**Comment by theRookieCoder** [comment]
Seems to only occur when the line is wrapped (console-rs/dialoguer#295)

**Comment by theRookieCoder** [comment]
I will close this issue since there's not much I can do, and it's not a major bug anyways.
