### ISSUE TITLE
Modpack and mods shouldn't exclude each others when upgrading

### ISSUE THREAD

**Issue by porkyoot** [gorilla-devs/ferium#389]
### The Problem

When you add a modpack to a profile and upgrade it, all mods gets removed regardless if they belong to the profile.The opposite is true. This makes adding mods and modpack into one profile very confusing.

### Your Solution(s)

I suggest removing the `ferium modpack upgrade` command and make it so `ferium upgrade` upgrades everything seamlessly.

**Comment by theRookieCoder** [comment]
Ferium does not have the ability to install custom mods to the modpacks it downloads, this is planned in #94
