### ISSUE TITLE
Add argument to specify the profile to switch to after deleting the current one

### ISSUE THREAD

**Issue by codethinki** [gorilla-devs/ferium#390]
### The Problem

i want to create a temporary profile which only changes the output path and then use this to download my mods to a different directory. but im having a hard time deleting my temporary profile without this "choose a profile to switch to" dialog which, as far as i understood, cannot be skipped nor auto chosen.

Would be nice to get some help :)

### Your Solution(s)

add an option to specify the "switch to" profile after deleting

**Comment by theRookieCoder** [comment]
If you want an identical profile but with a different output directory, I'd recommend just temporarily changing the output directory using `ferium profile configure`.

**Comment by codethinki** [comment]
yes but then all the profiles get listed and i have to process the output to find the correct profile and line and its just a pain in the ass would be much simpler with just specifying a profile to go to as argument

**Comment by theRookieCoder** [comment]
> much simpler with just specifying a profile to go to as argument

Hmm, ok I think I understand your problem much better now. Ideally the program should be able to run without any interactivity to allow for scripting and also for what you mentioned.

**Comment by theRookieCoder** [comment]
Fixed in 15e08f9c0185347bf736bf13ef5d874452ea0717
