### ISSUE TITLE
Supporting NeoForge

### ISSUE THREAD

**Issue by Aces-and-Jacks** [gorilla-devs/ferium#392]
### The Problem

I currently can only install forge mods but with NeoForge it would be nice if it got support. 

### Your Solution(s)

Add NeoForge support. 

I didn't see any issue so I figured it'd be ok to make this for anyone who wonders about it.

**Comment by Aces-and-Jacks** [comment]
Also mainly that a lot of the developers from forge moved to Neoforge

**Comment by theRookieCoder** [comment]
Can I confirm that after 1.20.1, NeoForge is no longer backwards compatible with Forge mods? For how many minecraft versions did they have backwards compatibility, and are there any significant amount of users still making use of backwards compatibility?

**Comment by Aces-and-Jacks** [comment]
From what I know of 1.20.1 is compatible with forge mods since that's when they split, and past that NeoForge is no longer compatible with forge
