### ISSUE TITLE
Directory picker does not work on linux cargo build

### ISSUE THREAD

**Issue by ARedstoneMan** [gorilla-devs/ferium#397]
### Description

On the cargo build of ferium, when trying to change the mods directory both when prompted on first profile creation using `ferium profile create` or when configuring a profile using `ferium profile configure`, it does not work as intended and completely skips asking for a new directory to change it to.

### Steps to reproduce

1. Set up ferium with cargo
2. Create a new profile using `ferium profile create`
3. When asked if you want a custom mods directory, answer yes
4. Take note of how it completely skips it  over as if you had answered no
5. After creating a profile, execute `ferium profile configure`
6. Take notice about how it does nothing when you select change mods directory in the selection bar and instead prints the selection bar again

### Operating System

Linux

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
Could I know what distro and desktop environment you're using?

**Comment by theRookieCoder** [comment]
I would recommend using the no-gui version (`cargo install ferium --no-default-features`) as a workaround.

**Comment by MrKoroshiya** [comment]
Hello! It's happening to me too on Debian 12 (no DE)

**Comment by theRookieCoder** [comment]
If you don't have a desktop environment, you need to use the no-gui version (or compile with `-=no-default-features`) to disable the GUI file dialogue and use a CLI interface instead.

**Comment by MrKoroshiya** [comment]
Thank you for your answer! Can I install the no-gui version using brew? I couldn't find instructions for it

**Comment by theRookieCoder** [comment]
Homebrew doesn't bottle the `no-gui` version, and unfortunately it seems you can't specify compiler flags when choosing to build from source when installing. I would recommend [installing rust](https://www.rust-lang.org/tools/install) and using cargo to build from source (with `--no-default-features`). You could also use the github release build but you'll have to manually update.

**Comment by MrKoroshiya** [comment]
Adding this for future readers of this issue: As an alternative, you can change the custom path in ferium's config file to continue using Homebrew

**Comment by theRookieCoder** [comment]
You can use the command line option `--output-directory` or `-o` when creating or configuring a profile to not use any sort of interactive interface at all too. This is preferable to manually editing the config file.

**Comment by ARedstoneMan** [comment]
Oh wow, this is a pretty simple solution. Maybe I completely missed this in the README but perhaps it's a good idea to make it more clear that you need this nogui option if you do not have an environment it can open?

**Comment by theRookieCoder** [comment]
Thanks for the feedback! I'll make the information more prominent soon.

> the commands for listing a custom directory

I don't exactly understand what you mean here?

Otherwise I'll just confirm that it didn't work for you because you did not have a gui and didn't use the nogui version? I think I can close this right?

**Comment by ARedstoneMan** [comment]
Yeap that's fine. That was just referring to an example of how and where this can be made more clear in the documentation so that people don't run into the same issue.
