### ISSUE TITLE
Check if mods in a profile are compatible with a specific version without upgrading them

### ISSUE THREAD

**Issue by VincyZed** [gorilla-devs/ferium#398]
### The Problem

Right now, if we want to verify what client-side mods are compatible with the next version of a server we want to upgrade to, we have to do the following workaround:

1. Change the Ferium profile version to the potential target version.
2. Launch Minecraft.
3. Run the `ferium upgrade` command, which will list what mods are incompatible. Since the game is running, no mods will be replaced as Ferium won't be able to delete the files.
4. Close Minecraft.
5. Set the Ferium profile back to the current version.

### Your Solution(s)

It would be cool if there was a command to display the compatibility for all the mods in a profile for a specific version!
Something like `ferium check-compatibility`, which would ask you what version of the game you would like to verify the compatibly with.

**Comment by theRookieCoder** [comment]
The dry-run feature of #49, along with the ability to override the game version for a single upgrade run should resolve this
