### ISSUE TITLE
Cannot add 1.20 mod to 1.20.1 instance

### ISSUE THREAD

**Issue by AlphaCraft9658** [gorilla-devs/ferium#401]
### Description

I should be able to add 1.20 mods to 1.20.1, as they're compatible with both versions. Floodgate supports 1.20, but not explicitly 1.20.1. Therefore, I cannot add the mod and ferium says it's incompatible.

### Steps to reproduce

Run `ferium add floodgate` on a Fabric 1.20.1 instance/server.

### Operating System

Linux

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
This should be resolved by using the minor game version filter specified [here](https://github.com/gorilla-devs/ferium/issues/155#issuecomment-1481303888), which will become the default.
