### ISSUE TITLE
Release v4.5.2 ferium-windows-msvc detected as Trojan:Win32/AgentTesla!ml

### ISSUE THREAD

**Issue by ST-DDT** [gorilla-devs/ferium#405]
### Description

Windows Defender detects the latest version as [Trojan:Win32/AgentTesla!ml](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin32%2FAgentTesla!ml&threatid=2147760503) (malware/virus)

### Steps to reproduce

- Download file on windows
- Try to unzip it
- Malware scanner raises alarm

### Operating System

Windows

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

### Additional Information

v4.5.1 is reportedly clean/not affected

**Comment by theRookieCoder** [comment]
I have submitted this as a false positive to Microsoft, I would urge anyone encountering this to also flag this as a false positive in their antivirus program.

The detection is made by AI (as indicated by the `!ml` flag at the end of the detection ID) and is prone to false positives, particularly for rust programs in my experience.

**Comment by theRookieCoder** [comment]
I believe ferium has been whitelisted by defender.

**Comment by ST-DDT** [comment]
4.6.0 gets reported as `Trojan:Win32/Phonzy.B!ml` again - `https://github.com/gorilla-devs/ferium/releases/download/v4.6.0/ferium-windows-msvc.zip`

**Comment by theRookieCoder** [comment]
Yes I noticed that in the winget package update, but it seems it didn't trigger in the second run? I've read a lot of rust programs being falsely flagged by defender. I _think_ maybe because of winget package updates, the defender team does whitelist the file.

**Comment by ST-DDT** [comment]
4.7.0 got flagged as well - https://github.com/microsoft/winget-pkgs/pull/157719
