### ISSUE TITLE
Add a way to check if updates are available without applying them

### ISSUE THREAD

**Issue by dr-vortex** [gorilla-devs/ferium#412]
### The Problem

It would be nice to have a method for checking whether updates are available without applying them. This would allow the user to check if updates are available while the game is running, since MC creates a lock on all of the mod jar files (which prevents writes).

### Your Solution(s)

This could be implemented with a command, `ferium status`. When run without any arguments, the command would check for updates against all of the mods and modpacks in the current project. Otherwise, it could take a list of project IDs and check those.

**Comment by theRookieCoder** [comment]
Duplicate of #49
