### ISSUE TITLE
'The project is not compatible', but it is not true

### ISSUE THREAD

**Issue by nekobread4** [gorilla-devs/ferium#417]
### Description

I tried to add this mod:
https://www.curseforge.com/minecraft/mc-mods/immersiveposts
with Forge 1.12.2 ferium config.
"ferium add 314645"
: "The project is not compatible"
but it has version for 1.12.2 forge
https://www.curseforge.com/minecraft/mc-mods/immersiveposts/files/2951672

### Operating System

Linux

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
Use `--ignore-mod-loader`. CurseForge doesn't mandate that you specify the mod loader so some older mods on older minecraft version just assume forge and don't specify it.

**Comment by nekobread4** [comment]
ferium add 314645 --ignore-mod-loader
: Adding mod... The project is not compatible

**Comment by nekobread4** [comment]
@theRookieCoder

**Comment by theRookieCoder** [comment]
https://github.com/gorilla-devs/libium/blob/e11a80bc57c5cda6fa3605ba3b96a1b2563760f9/src/add.rs#L297

There's a bug in the adding code. I've rewritten this code already, so it should be fixed in the next update.

**Comment by theRookieCoder** [comment]
You should be able to do `ferium add 314645 --ignore-mod-loader --force` to add the mod anyways and the upgrade command should work as usual.

**Comment by theRookieCoder** [comment]
Fixed in 3baa0c64bc558c77890fdccf075d88bd155cc16b
