### ISSUE TITLE
[BUG] Ferium is not installing the proper mods

### ISSUE THREAD

**Issue by otter501** [gorilla-devs/ferium#420]
### Description

Ferium is not upgrading [Sodium Extra](https://modrinth.com/mod/sodium-extra) to the most recent version, it is downloading 0.5.6 instead of 0.5.7

It also is not installing dependencies (TCDCommons API) when I add the [Better Statistic Screen](https://modrinth.com/mod/better-stats) mod, but Prism Launcher does install it as a dependency

### Operating System

Linux

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
> It also is not installing dependencies

Dependencies will be added (hopefully soon) in #214

Could I know what game version and mod loader you have in your profile? Sodium Extra `0.5.7` is only for `1.21`.

**Comment by otter501** [comment]
I am using Quilt and am on 1.21 (i manually am using fabtic api because qfapi is not ready yet) also, its not a recursive dependency, its a direct dependency

**Comment by otter501** [comment]
There is a chance is something to do with 1.21 because Better Statistic Screen only requires TCDCommons in 1.21

**Comment by theRookieCoder** [comment]
The reason is Sodium Extra `0.5.6` is marked to support Quilt, but `0.5.7` isnt't. The author should update the version metadata properly for it to work.
