### ISSUE TITLE
GitHub repositories aren't working with Ferium

### ISSUE THREAD

**Issue by Trojan-V** [gorilla-devs/ferium#427]
### Description

Every single GitHub repository (besides one) I tried so far didn't work with Ferium.
Are all of these actually not compatible, or is this a Ferium issue?
I have my own GITHUB_TOKEN set through the environmental variables of my operating system.

These are a few of the mods I tried: 
https://github.com/Skytils/SkytilsMod
https://github.com/IndigoPolecat/BingoBrewers/

This mod worked for some reason: https://github.com/BananaFructa/Apec

Can someone explain the difference between these GitHub repositories,  and especially why the last mod works while the other ones doesn't.

Thanks in 

### Steps to reproduce

To reproduce the behavior, run the following commands (after a profile was created of course):
The first two commands should return the error message "The project is not compatible: Skytils/SkytilsMod" and "The project is not compatible: IndigoPolecat/BingoBrewers".
`ferium add Skytils/SkytilsMod`
`ferium add IndigoPolecat/BingoBrewers`

The third command should return the success message "Successfully added BananaFructa/Apec".
`ferium add BananaFructa/Apec`

Please let me know where the difference between these are.

### Operating System

Windows

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
The issue with both is that they don't have the game version and mod loader in the filename.
Unfortunately, ferium can't figure out the game version or mod loader any other way at the moment. You can use `--ignore-mod-loader --ignore-game-version` to always download the latest release if that works for you.

**Comment by theRookieCoder** [comment]
Should be resolved by #155
