### ISSUE TITLE
The following mod(s) have denied 3rd parties such as Ferium from downloading it

### ISSUE THREAD

**Issue by Trojan-V** [gorilla-devs/ferium#428]
### Description

Can anyone help me on how to fix the following issue?
And, is there a possibility to add my own mods to a modpack to customize it?

The following mod(s) have denied 3rd parties such as Ferium from downloading it
- Ender Dragon Revamp
  https://www.curseforge.com/minecraft/texture-packs/ender-dragon-revamp/download/4333759
- Better With Minecolonies [Forge]
  https://www.curseforge.com/minecraft/mc-mods/better-with-minecolonies/download/3987740
- Wabi-Sabi Structures (Forge)
  https://www.curseforge.com/minecraft/mc-mods/wabi-sabi-structures-forge/download/4688278
- STONEBORN - Modded Compatibility GUI - SBMC
  https://www.curseforge.com/minecraft/texture-packs/stoneborn-modded-compatibility-sbmc/download/4373196
- Structory: Towers
  https://www.curseforge.com/minecraft/mc-mods/structory-towers/download/4441351
- Towers of the Wild Modded
  https://www.curseforge.com/minecraft/mc-mods/towers-of-the-wild-modded/download/5239657
- Entity Culling Fabric/Forge
  https://www.curseforge.com/minecraft/mc-mods/entityculling/download/4404949
- Structory
  https://www.curseforge.com/minecraft/mc-mods/structory/download/4441631

### Steps to reproduce

ferium modpack add 957753
ferium modpack upgrade

### Operating System

Windows

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
Those mods have set an option such that they can only be downloaded from the curseforge website or app. You can add mod files manually into the `user` subfolder in the output directory ([documentation](https://github.com/gorilla-devs/ferium?tab=readme-ov-file#user-mods)).
