### ISSUE TITLE
Thaumcraft is not compatible?

### ISSUE THREAD

**Issue by xronin01** [gorilla-devs/ferium#429]
### Description

![Screenshot_20240823-104456_TermuxMonet](https://github.com/user-attachments/assets/23b53f0b-bfa3-4e26-9e28-5fbad4040e28)

### Operating System

other (Specify in Additional Information)

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
You need to use `--ignore-mod-loader` since Thaumcraft does not explicitly specify that it uses Forge.
