### ISSUE TITLE
ferium can't download mods from github

### ISSUE THREAD

**Issue by xronin01** [gorilla-devs/ferium#430]
### Description

![Screenshot_20240823-163345_TermuxMonet](https://github.com/user-attachments/assets/35d91e46-c522-4cc1-b6e0-880f5e42f308)
https://github.com/GTNewHorizons/TinkersConstruct

### Operating System

other (Specify in Additional Information)

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
The repository you linked does not have Releases
