### ISSUE TITLE
Support for paper plugins

### ISSUE THREAD

**Issue by HoldYourWaffle** [gorilla-devs/ferium#431]
### The Problem

It'd be great if I could use ferium to manage the plugins for paper-based servers as well.

### Your Solution(s)

This relates to #90 and #425, but at the core the mechanics for paper are the same as the other modloaders.

**Comment by theRookieCoder** [comment]
Duplicate of #275

**Comment by HoldYourWaffle** [comment]
Whoooops, I shouldn't make issues at 3am...
