### ISSUE TITLE
ferium scan command does not work

### ISSUE THREAD

**Issue by afawe3331** [gorilla-devs/ferium#435]
### Description

✔ Output Directory · /Users/*/Library/Application Support/PrismLauncher/instances/1.21/.minecraft/mods
There are files in your output directory, these will be deleted when you upgrade.
✔ Would like to create a backup? · no
✔ What should this profile be called? · fa
✔ Which version of Minecraft do you play? · 1.21
✔ Which mod loader do you use? · Fabric
After adding your mods, remember to run `ferium upgrade` to download them!
❯ ferium scan
error decoding response body

### Steps to reproduce

1.❯ ferium scan
error decoding response body

### Operating System

macOS

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
Could you provide the mods you're scanning, either here or personally on Discord (`therookiecoder`) if you prefer.

**Comment by afawe3331** [comment]
> Could you provide the mods you're scanning, either here or personally on Discord (`therookiecoder`) if you prefer.

I tried loading a forge instance folder for testing and it worked fine.
I then loaded the existing fabric instance again and it worked fine, without the error I mentioned above. I didn't reboot or make any other changes, so I don't know why that error happened or why it was resolved. I'll close the issue for now.
