### ISSUE TITLE
Adding/Importing mods via Github does not work properly

### ISSUE THREAD

**Issue by KavyanshKhaitan2** [gorilla-devs/ferium#440]
### Description

When trying to add any mod by its github URL, ferium drops this error for me.
![image](https://github.com/user-attachments/assets/6e826304-c812-4300-81d8-a52e09077de1)
I am guessing a simple fix to this would be to allow authentication for Github.

### Steps to reproduce

1. Create any ferium profile
2. Run `ferium add RedLime/SleepBackground` or `ferium add fxmorin/moreculling`

### Operating System

Windows

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
GitHub has pretty strict rate limits for unauthenticated requests, 60 per hour to be specific. If you have lots of github mods it's easy to cross that.

Ferium has the option to add a github authentication token ([documentation](https://github.com/gorilla-devs/ferium?tab=readme-ov-file#overview--help-page), which increases the limit to 5000 per hour.

**Comment by KavyanshKhaitan2** [comment]
@theRookieCoder I didnt use a Github mod at all. I am guessing it is something else on the network causing that. Thanks tho!

**Comment by theRookieCoder** [comment]
Huh, you are adding a github mod in the picture you attached.

**Comment by KavyanshKhaitan2** [comment]
I meant a lot of github mods. Sorry for the typo!
