### ISSUE TITLE
No option for installing the no-gui version via Homebrew

### ISSUE THREAD

**Issue by FileOfName** [gorilla-devs/ferium#441]
### Description

Currently, Homebrew does not provide an option to install the no-gui version, which results in file picker prompts causing the terminal to hang. On other Linux distributions, the GUI is disabled by default. The AUR provides both versions, which would be beneficial for Homebrew, especially since it is also used on macOS.

### Operating System

Linux

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment]
It is not possible to do this in homebrew.

**Comment by theRookieCoder** [comment]
It is also not possible to configure cargo features when building from source in homebrew. These are all limitations of homebrew that I can't control.

There use to be an 'options' feature but it was very controversially removed.
