### ISSUE TITLE
Chocolate Minecraft Source

### ISSUE THREAD

**Issue by ok-coder1** [gorilla-devs/ferium#446]
### The Problem

Everytime I have BetterPVP installed, whenever I run `ferium upgrade`, it moves the mod to the `.old` folder and I have to drag it back to the `mods` folder.

### Your Solution(s)

Adding the source: https://chocolateminecraft.com

**Comment by theRookieCoder** [comment]
Use the [user mods](https://github.com/gorilla-devs/ferium#user-mods) feature to manually add mod files. I'm not interested in adding sources that are by a specific mod author, and the website does not have a documented API anyways.

**Comment by ok-coder1** [comment]
> Use the [user mods](https://github.com/gorilla-devs/ferium#user-mods) feature to manually add mod files.

I didn't know such a feature existed, thanks!
