### ISSUE TITLE
Modpack not download (4.7.1)

### ISSUE THREAD

**Issue by Rushmore75** [gorilla-devs/ferium#448]
### Description

Trying to download [this modpack](https://modrinth.com/modpack/landscapes-reimagined-genesis), it downloads the manifest file ok, then **Downloading 299 mods** and stalls out, downloading nothing, no network traffic.

### Steps to reproduce

```bash
ferium modpack add landscapes-reimagined-genesis
ferium modpack install
```

### Operating System

Linux

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

### Additional Information

Testing on Ubuntu & EndeavourOS

**Comment by theRookieCoder** [comment]
This bug (#432) was introduced in the latest version, you can use the previous version `v4.7.0` if you need to download more than 75 mods.
