### ISSUE TITLE
Scan the output directory and add mods found to the profile

### ISSUE THREAD

**Issue by theRookieCoder** [gorilla-devs/ferium#57]
Modrinth has the functionality to find out which `Version` a local file belongs to (https://docs.modrinth.com/api-spec/#operation/versionFromHash)  
CurseForge seems to have this functionality through 'fingerprints' but I haven't figured it out yet
Functionality for this in GitHub Releases is not possible

**Comment by KyleUltimate** [comment]
So if this is added, which also means hash checking getting added too?
https://github.com/theRookieCoder/ferium/issues/34#issuecomment-1114710687
https://github.com/theRookieCoder/ferium/issues/49#issuecomment-1120360382
I think these two can also be added via the same logic
Well for github releases, maybe say something on README that it doesn't have as much functionality so use modrinth, curseforge, and then github releases

**Comment by KyleUltimate** [comment]
ALso which platform should we use first?
I guess modrinth would be great. But there is a slight problem with that.
Because modrinth isn't the first platform of choice for mod developers, some mod developers will have slower update cycles on modrinth.
I've encountered such problem before but I forgot which mods had them

**Comment by theRookieCoder** [comment]
> which also means hash checking getting added too?

Yes, the age old problem will be fixed

**Comment by theRookieCoder** [comment]
As suggested in #64, we should also support adding mods from a file

**Comment by Cloudate9** [comment]
Hey there, @theRookieCoder 

I'm one of the main developers of [ReviversMC/the-mod-index](https://github.com/ReviversMC/the-mod-index), and, although it seems you have a plan for adding this functionality, I'd like to propose our repo for helping you out.

While it is **not** yet complete, we're pretty dang close, and I think It'd help you a lot!  
We currently do not have a Rust api though, but simple http calls do GitHub will do the job (api contributions always welcome)

If you'd like to get in touch with us for more details, you can find us on [Discord](https://discord.gg/6bTGYFppfz) :slightly_smiling_face:

**Comment by kappa-maintainer** [comment]
I found another project that has implemented this feature for some time: https://github.com/packwiz/packwiz

**Comment by Bluscream** [comment]
I consent with this request!

**Comment by ipiiia** [comment]
Has this feature been added yet?

**Comment by Bluscream** [comment]
Chill. Its been only a year. Give them atleast till minecraft 1.40

**Comment by PockySweet** [comment]
One day it will happen!

**Comment by theRookieCoder** [comment]
It will be soon since the primary blocking issue for this (#175) has been resolved!

**Comment by theRookieCoder** [comment]
I've implemented the feature, I'll test and release it hopefully by tomorrow.

https://fosstodon.org/@theRookieCoder/112597787974114828

**Comment by theRookieCoder** [comment]
You can try it out now by compiling from the repo or using the [actions artefacts](https://github.com/gorilla-devs/ferium/actions/runs/9465746632).
