### ISSUE TITLE
Collapse all three add commands into one add command

### ISSUE THREAD

**Issue by theRookieCoder** [gorilla-devs/ferium#65]
This would be possible since if the ID
- Has a slash, it's a GitHub repository
- Is a number, it's a CurseForge project
- Else it's a Modrinth project

**Comment by KyleUltimate** [comment]
A question: Is it not possible to add curseforge mods via their "slugs"?(the name in the url)

**Comment by theRookieCoder** [comment]
It might be but CF's api does not say that you can get the mod from the slug anywhere in [their documentation](https://docs.curseforge.com). If you discover semething like this, please let me know!

**Comment by KyleUltimate** [comment]
https://docs.curseforge.com/#search-mods
It seems it like it has search #slug.
Maybe use it and get the mod id?

**Comment by theRookieCoder** [comment]
Hmm but this would directly interfere with this enhancement. And Furse doesn't support search calls yet. But yeah it would be helpful

**Comment by KyleUltimate** [comment]
Maybe if getting a slug, ferium checks both modrinth and curseforge. And if both mods have the exactly same slug on both platforms, give the user a prompt asking which platform would they want to use

**Comment by theRookieCoder** [comment]
Yeah that would work, the problem is that add command in general is already terribly slow. This would make it worse, but oh well it would be more convenient.
