### ISSUE TITLE
Improve GitHub modloader checks

### ISSUE THREAD

**Issue by JustSimplyKyle** [gorilla-devs/ferium#66]
### Discussed in https://github.com/theRookieCoder/ferium/discussions/58

<div type='discussions-op-text'>

<sup>Originally posted by **KyleUltimate** May 10, 2022</sup>
For ~~almost~~ all the github mods I use, I have to add `--dont-check-modloader`. How does the current checking works?</div>
The discussion in https://github.com/theRookieCoder/ferium/discussions/58 has a slight hint of how this could be implemented

**Comment by theRookieCoder** [comment]
Moved to #155
