### ISSUE TITLE
Build with XDG Desktop Portal GUI backend on Linux

### ISSUE THREAD

**Issue by ImperatorStorm** [gorilla-devs/ferium#77]
While the [`rfd`](https://docs.rs/crate/rfd/latest/features) crate provides both GTK3 and [xdg-desktop-portal](https://docs.rs/rfd/latest/rfd/#xdg-desktop-portal-backend) backends, Ferium only builds the GTK3 backend, causing non-Gnome users to see this mess of a filechooser that likely doesn't conform to their desktop environment: ![GTK filechooser](https://user-images.githubusercontent.com/30777770/168449243-368f2caa-3c3f-4c51-84e7-d09c389c4315.png)

Programs that do support the specification(e.g. Firefox+derivatives) instead provide a file chooser provided by their desktop environment. For example, Plasma provides this:
![Plasma filechooser](https://user-images.githubusercontent.com/30777770/168449316-33dcd343-a8e5-4e9b-96dd-157036a044dc.png)

Depends on https://github.com/PolyMeilex/rfd/issues/42, which in turn depends on https://github.com/flatpak/xdg-desktop-portal/issues/796

**Comment by theRookieCoder** [comment]
@KyleUltimate I'm going to make three linux binaries
- `ferium-linux-gnu-nogui`
- `ferium-linux-gnu-gtk`
- `ferium-linux-gnu-xdg`

What do you think? Do you think these will work out for the AUR packages?

**Comment by theRookieCoder** [comment]
Oof the xdg backend just added like 20 dependencies

**Comment by KyleUltimate** [comment]
Should be fine, I'll just separate the `-gui` packages into `-xdg` and `-gtk3`

**Comment by KyleUltimate** [comment]
Although for current `-gui` users, should they automatically migrate to xdg or gtk?

**Comment by KyleUltimate** [comment]
Also, is this package opended by gorilla's dev?
https://aur.archlinux.org/packages/ferium

**Comment by theRookieCoder** [comment]
> Also, is this package opended by gorilla's dev? https://aur.archlinux.org/packages/ferium

Nope, I have no idea what that is or who uploaded it. It's not even named properly. Oh and it seems to a `bzip2` dependency which is you should probably add, it was added for unzipping modpack files

**Comment by theRookieCoder** [comment]
I think I'll email the guy and tell him that there are already official AUR packages

**Comment by theRookieCoder** [comment]
> should they automatically migrate to xdg or gtk

Is it possible to let them choose? If not choose one based on which DE is used most in arch

**Comment by KyleUltimate** [comment]
Hmm
Then I'll use xdg for default then
Since that will work no matter on gnome or plasma

**Comment by theRookieCoder** [comment]
> Since that will work no matter on gnome or plasma

Yeah I read something like this somewhere. So is the GTK backend completely unnecessary?

**Comment by KyleUltimate** [comment]
I think yeah

**Comment by theRookieCoder** [comment]
Fixed by b8b272515232c0ddb76dd2d992ff79381393a207
