### ISSUE TITLE
Not able to add Ars Creo even though it is compatible

### ISSUE THREAD

**Issue by theRookieCoder** [gorilla-devs/ferium#78]
From #76

**Comment by theRookieCoder** [comment]
<img width="1122" alt="Screenshot 2022-05-15 at 10 18 14 AM" src="https://user-images.githubusercontent.com/60034030/168457725-e070c2f0-c938-4c04-b8e5-6215712b3c1f.png">
CurseForge API seems to not be working properly (again #41). The game versions list is empty for some reason. Ugh why can't everyone use Modrinth^1^

^1^ I know that they don't have developer payouts and that their UI's error handling sucks

**Comment by theRookieCoder** [comment]
API is still broken, there's absolutely nothing I can do about this so I'm going to close this for now

**Comment by KyleUltimate** [comment]
Maybe tag wont-fix would be better?
It's up to you tho
