### ISSUE TITLE
Config file is not read properly when it's first created

### ISSUE THREAD

**Issue by Remynfv** [gorilla-devs/ferium#87]
Running the `ferium list` command before any mods are installed shows the error:
`EOF while parsing a value at line 1 column 0`

Maybe this could show a message like `There are 0 mods installed! Type <command> to get started!`

EDIT: Very strange, the SECOND time I run this command, it shows a nice message! "There are no profiles configured. Add a profile to your config using `ferium profile create`".

**Comment by theRookieCoder** [comment]
Yes this is a knowm bug. The problem is that when it first creates the config file it doesn't read it properly

**Comment by daenney** [comment]
I ran into a similar instance, with a new ferium install:

```
$ cat ~/.config/ferium/config.json
cat: /home/daenney/.config/ferium/config.json: No such file or directory

$ ferium profile create --mod-loader quilt --name default --game-version 1.19
EOF while parsing a value at line 1 column 0

$ cat ~/.config/ferium/config.json
{
  "active_profile": 0,
  "active_modpack": 0,
  "profiles": [],
  "modpacks": []
}⏎                                                                                                                                       

$ ferium profile create --mod-loader quilt --name default --game-version 1.19
After adding your mods, remember to run `ferium upgrade` to download them!

$ cat ~/.config/ferium/config.json
{
  "active_profile": 0,
  "active_modpack": 0,
  "profiles": [
    {
      "name": "default",
      "output_dir": "/home/daenney/.minecraft/mods",
      "game_version": "1.19",
      "mod_loader": "Quilt",
      "mods": []
    }
  ],
  "modpacks": []
}⏎      
```

**Comment by theRookieCoder** [comment]
I managed to replicate the bug in [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=96db779ea6c5e0daaf1c770afd37829d)
