### ISSUE TITLE
Unhide the `--config-file` flag

### ISSUE THREAD

**Issue by imsofi** [gorilla-devs/ferium#91]
Im planning to use this program to manage a server's installed mods, and several users may be able to touch this server's configuration file. It is quite annoying to try and keep a single global `~/.config/ferium/config.json` file in sync for the server, but also let people have their own personal mod profiles not sync over.

I propose that there would be added an option, `--config-file`, which would heavily simplify this use-case. Letting one for example have the mod list config.json file be easily versioned trough a git repo, and you can run `ferium --config-file=ferium-mods.json` to use that specific folder's json file instead of the global one.

There may be some issues regarding how to properly point to the output location. One solution could be to allow relative output folders. Another would be the introduction of a second option as well, `--download-location` to define it at the command level. I am open to hearing other ways to solve this. As the global config is really nice to manage one computer's mods and modpacks. It however quickly falls apart if you want to manage either another computer's mods (think server) and/or you are collaborating between several people.

**Comment by theRookieCoder** [comment]
Actually I already implemented this for the integration tests :)

It was hidden though, I'll unhide it now

**Comment by theRookieCoder** [comment]
Fixed by b8b272515232c0ddb76dd2d992ff79381393a207
