### ISSUE TITLE
[Enhancement] Support for No GUI systems such as VMs for Minecraft Servers

### ISSUE THREAD

**Issue by A-noximous** [gorilla-devs/ferium#93]
Ferium is a great mod manager to use on the client side, but would not work very well on server hosting systems, considering the fact that the alternate mod output directory dialog opens in File Explorer(Windows) and most Minecraft Servers are hosted on cloud services without GUI support.

**Comment by theRookieCoder** [comment]
There are no gui builds for Linux, you can use those for server use. Afaik no one will use anything other than Linux for servers

**Comment by KyleUltimate** [comment]
You could sorta workaround this by using `--output-dir` and other

**Comment by theRookieCoder** [comment]
Yes you can also bypass the interactive prompts by using the options when needed
