### ISSUE TITLE
Merge projects?

### ISSUE THREAD

**Issue by obj-obj** [gorilla-devs/ferium#97]
Are there any plans to make a launcher portion to this project?

I'm currently working on a Minecraft launcher at https://github.com/obj-obj/copper_rs. I just realized this existed, and I don't really like fragmentation, so I'd like to help if there are any plans to make a launcher portion to this mod manager.

I also have some ideas to improve this project such as building mods from git automatically and symlinking or hardlinking mods, resource packs, etc. across profiles to deduplicate as much as possible.

**Comment by theRookieCoder** [comment]
> Are there any plans to make a launcher portion to this project?

Yes! The goal is to have Ferium and GDLauncher's GUI version have feature parity, but with two different interfaces.

I'll see what we can do about merging.

**Comment by KyleUltimate** [comment]
> building mods from git automatically
I think this should be done more like "bash script" instead of like doing them fully automatically. Most mod with work with just `./gradlew build`, but there are exceptions.
Such as gradlew not being set as exec, requires other mods in local maven(old iris-sodium), using alternative build systems(iris), special mod names(-all). In short, if you want to make building mods automatically, you have to deal with a lot of exceptions, and have to make a lot of hard coding. But with scripting, it's up to the user to build it, and fix their scripts

**Comment by obj-obj** [comment]
> > building mods from git automatically
> 
> I think this should be done more like "bash script" instead of like doing them fully automatically. Most mod with work with just `./gradlew build`, but there are exceptions. Such as gradlew not being set as exec, requires other mods in local maven(old iris-sodium), using alternative build systems(iris), special mod names(-all). In short, if you want to make building mods automatically, you have to deal with a lot of exceptions, and have to make a lot of hard coding. But with scripting, it's up to the user to build it, and fix their scripts

I mean more like basic support, just running chmod +x gradlew and ./gradlew build, and giving an error if it fails to build

**Comment by obj-obj** [comment]
> > Are there any plans to make a launcher portion to this project?
> 
> Yes! The goal is for Ferium and GDLauncher's GUI version to have feature parity, but with two different interfaces.
> 
> I'll see what we can do about merging (please contact me on Discord: `theRookieCoder#1287`)

I'm building my launcher like a library with a seperate CLI crate for testing, so it should be possible to use it if I document and clean up the API after finishing authentication

**Comment by obj-obj** [comment]
Also for GUI we could use https://tauri.studio as there aren't really any good gui libraries in Rust right now

Or expose the libraries as a C API and use QT

**Comment by obj-obj** [comment]
Oh there's already plans to make the rewrite in tauri, ok then

**Comment by theRookieCoder** [comment]
I'm going to close this for now since this isn't a bug or enhancement

**Comment by illnyang** [comment]
https://squiddev.cc/maven/cc/tweaked/

@theRookieCoder 
you won't find CC:Tweaked fabric builds anywhere else, why did you close this issue again?

**Comment by theRookieCoder** [comment]
> CC:Tweaked

Sorry I have no idea what this is?? Please create a new issue or discussion if you'd like to talk about it since it doesn't seem to be related to this issue.

> Why did you close this issue again?

The answer is [right above your comment](https://github.com/gorilla-devs/ferium/issues/97#issuecomment-1140419267).

**Comment by illnyang** [comment]
> Please create a new issue or discussion if you'd like to talk about it since it doesn't seem to be related to this issue.

note to myself: never write anything online before drinking the morning coffee. i_really_ badly misread this issue, sorry for that. 

i have opened a new feature request issue.

**Comment by killpowa** [comment]
Hi @obj-obj, would you mind contacting me on discord? (Davide#1234)

**Comment by theRookieCoder** [comment]
No problem!

And thanks for the suggestion
